const pageDatabase = {
    Methods: {
        fa: {
            title: "تار برگ آیین",
            text: [
                " به تار برگ آیین خوش آمدید. این بخش ساختار اصلی صفحات وب را تشکیل می‌دهد.",
                "برای نزدیک‌تر کردن این پیش‌نویس به کشورهای پادشاهی مشروطه‌ی پیشرفته و مدرن (مانند سوئد، نروژ و بریتانیا)، چند ابزار حقوقی و عملی به متن افزوده شده است:",
                "",
                "۱. مدل پادشاهی سوئد (قانون اساسی ۱۹۷۴): در سوئد، پادشاه حتی دیگر نخست‌وزیر را رسماً معرفی نمی‌کند و این خویشکاری بر عهده سالار انجمن (رئیس پارلمان) است. این بالاترین سطح تفکیک قدرت برای جلوگیری از تمرکز قدرت در دست یک تن است.",
                "۲. مکانیسم دادرس مردمی (Ombudsman): برآمده از حقوق مدرن اسکانیا (سوئد) برای نظارت مستقیم مردم بر کارکرد دستگاه‌های دولتی.",
                "۳. سیستم پادشاهی بریتانیا: تمرکز بر سنت‌های پارلمانی و پاسخگویی تام کارگزاران اجرایی.",
                "در ادامه، متن کامل بازنویسی‌شده با واژگان سره و ذکر سرچشمه‌ها (شامل کشورهای پیشرفته) آمده است:",
                " آیین ریشه‌ای شاهنشاهی مشروطه مردم‌سالار ایران",
                " آمیزش ساختار مشروطه، مردم‌سالاری امروزی، الگوهای اسکانیا (سوئد) و ارزش‌های بوم‌آور",
               "",
                " بخش نخست: پایه‌های ارزشی و بنیادهای دستگاه",
               "",
                "<b>بند ۱:  والاییِ سرشت انسان و آزادی خواست</b>",
                "   بر پایه خرد آزاد انسان، والایی، حقوق بنیادین و آزادیِ خواستِ (اراده) همه شهروندان ایران، گزندناپذیر و سلب‌نشدنی است. آرمانِ غاییِ فرمانروایی، فراهم آوردن بستری شکوفا برای بهزیستی، شادی و رشد مادی و مینوی (هئوروتات) همگان است.",
                
                "<b>بند ۲: سرچشمه و درون‌مایه فرمانروایی ملی</b>",
                "   فرمانروایی، تنها و بی‌هیچ قید و شرطی از آنِ ملت ایران است که به شیوه مردم‌سالار، بخش‌بخش‌شده (غیرمتمرکز) و از راه صندوق رای و نهادهای انتخابی به کار بسته می‌شود. هیچ نهاد سنتی، باورمدار، موروثی یا ارتشی، حق غصب، ایست یا محدود کردن فرمانروایی ملی را ندارد.",
               
                "<b>بند ۳: فرمانروایی داد و راستی (اشا)</b>",
                " داد (قانون)، نمود خواست و خردِ همگانی ملت است. همه دادها، آیین‌نامه‌ها و داوری‌های دادگاه‌ها باید هماهنگ با اصول راستی، دادگریِ دانش‌محور، پیمان‌نامه جهانی حقوق بشر و پایداری زیست‌بوم (اشا) باشند. هیچ سرچشمه یا مصلحتی فراتر از داد نیست",
                "",
                "## بخش دوم: جایگاه، مرزها و خویشکاری‌های نمادین شاهنشاهی مشروطه (بر پایه الگوی پادشاهی سوئد)",
                
                "<b>بند ۴: ماهیت نمادین و جدایی تام شاه از قدرت</b>",
                "   بر پایه الگوی ساختار مشروطه سوئد (ریگسداگ ۱۹۷۴)، شاهنشاهی مشروطه، نهادی است سراپا نمادین و بی‌بهره از هرگونه نیروی سیاسی، دادگذاری، اجرایی و داوری. شاه نماد همبستگی ملی، پیوستگی تاریخی و دوستی میان همه تبارها و توده‌های ایران (پاسدار آرمَیْتی) است و از هرگونه دخالت در امور حاکمیتی بازداشته می‌شود.",
               
                "<b>بند ۵: حذف اختیارات اجرایی و معرفی نخست‌وزیر</b>",
                "   به پیروی از دادهای پیشرفته اسکانیا (سوئد)، شاه هیچ نقشی در گماشتن فرماندهان ارتشی یا معرفی نخست‌وزیر ندارد. خویشکاری معرفی نخست‌وزیر و مأمور تشکیل دولت، سراپا بر عهده «سالار انجمن نمایندگان» (رئیس پارلمان) است که برآمده از رأی مردم است. دستینه (امضا) کردن دادها از سوی شاه نیز تنها کاری تشریفاتی است و او حق وازدن (وتوی) هیچ دادی را ندارد.",
               
                "<b>بند ۶: چگونگی برکناری یا کناره‌گیری شاه</b>",
                "در صورتی که شاه به داوریِ دیوان عالی کشور یا رای دو سوم هموندانِ (اعضای) انجمن، از مرزهای آیین ریشه‌ای فراتر رود یا سوگند خود را بشکند، خودبه‌خود برکنار می‌شود. سپس انجمن درباره تداوم، دگرگونی شخص یا همه‌پرسیِ ساختارِ نهاد تصمیم می‌گیرد.",
               "",
                " بخش سوم: حقوق بنیادین، آزادی‌ها و زنهارنامه‌های شهروندی",
               
                "<b>بند ۷: برابری فراگیر زن و مرد، تبارها و باورها</b>",
                "همه شهروندان ایران، چه زن و چه مرد، فارغ از تبار، زبان، قومیت، نژاد، نگرش‌های فلسفی، باوری، سیاسی یا گرایش‌های فردی، در برابر داد کاملاً برابرند. اعمال هرگونه برتری‌دهیِ سازنده به سود گروه‌های به حاشیه رانده‌شده تاریخی برای برقراری دادگری راستین، دادین (قانونی) است.",
                
                "<b>بند ۸: گزندناپذیری وجدان (دَئِنا) و سراچه خصوصی</b>",
                " وجدان، باور و دینِ کسان، قلمرویی کاملاً فردی و آزاد است. تفتیش عقاید و داشتن دین رسمی در آیین ریشه‌ای ممنوع است. خانه، نامه‌نگاری‌ها، پیوندهای رایانه‌ای (دیجیتال) و حریم شخصی شهروندان از هرگونه تاخت‌وتاز، شنود و بازرسی خودسرانه بدون دستورِ روشن و مستدلِ دادگستری مصون است.",
               
                "<b>بند ۹: آزادی بیان، رسانه و دسترسی به آگاهی‌ها</b>",
                "  آزادی اندیشه، بیان، چاپ، هنر و روزنامه‌ها تضمین می‌شود. مهار و سانسور پیش از انتشار ممنوع است. انحصار رسانه‌های شنیداری و دیداری در دست دولت یا نهاد شاهنشاهی نامشروع است. همه شهروندان حق دسترسی آزاد و بدون فیلتر به جریان آزاد آگاهی‌ها و تارنمای (اینترنت) جهانی را دارند.",
                
                "<b>بند ۱۰: امنیت دادگاهی، منع شکنجه و اصل بی‌گناهی</b>",
                "هر متهمی بی‌گناه انگاشته می‌شود مگر اینکه بزهکاری او در دادگاهی علنی، با حضور هیئت منصفه و با حق داشتن وکیل مستقل پایدار شود. هرگونه آزار جسمی یا روانی (شکنجه)، به اقرار واداشتن، زندان انفرادی درازمدت و رفتارهای ضدانسانی مطلقاً ممنوع است و آسیب‌رسانان بدون شمول مرور زمان بازخواست می‌شوند.",
               "",
                "بخش چهارم: ساختار خرد جمعی (دستگاه دادگذاری دو انجمنی)",
                
                "<b>بند ۱۱: انجمن نمایندگان ملت</b>",
                "این انجمن از نمایندگان برگزیده مردم از راه انتخابات سراسری، آزاد، پنهان، دوره‌ای و بر پایه روش تناسبی پدید می‌آید. خویشکاری اصلی این انجمن، وضع دادهای معمولی، تصویب بودجه کشور، رای استوار به نخست‌وزیر و نظارت بر ارکان دولت است.",
                
                "<b>بند ۱۲: انجمن سنای استانی و کارشناسی</b>",
                " این انجمن از نمایندگان برابرِ استان‌ها و نخبگان علمی/تخصصی کشور تشکیل می‌شود تا از منافع بومی و توسعه پایدار استان‌ها در سطح کلان پدافند کند. هیچ دادی بدون بررسی در هر دو انجمن به تصویب نهایی نمی‌رسد تا از تمرکز قدرت جلوگیری شود (وهومن).",
               "",
                "بخش پنجم: دستگاه اجرایی و دولت خادم (خْشَثرَ)",
                
                "<b>بند ۱۳: چگونگی پدید آمدن دولت و پاسخگویی (الگوی مشروطه بریتانیا)</b>",
                "سالار دولت، نخست‌وزیر است. راهبر حزب یا ائتلافی که بیشترین کرسی‌های انجمن نمایندگان را به دست آورد، مأمور پدید آوردن کابینه می‌شود. دولت تماماً در برابر انجمن پاسخگو است و انجمن نمایندگان می‌تواند در هر زمان با رای عدم اعتماد، دولت یا هر یک از وزیران را برکنار کند.",
                
                "<b>بند ۱۴: مهار نیروی اجرایی و ارتش</b>",
                "نیروهای ارتشی، مرزبانی و امنیتی باید کاملاً غیرسیاسی، غیرجناحی و تحت نظارت و فرمان مستقیم دولت غیرارتشی و انجمن عمل کنند. دست‌اندازی نیروهای مسلح در کارهای اقتصادی، بازرگانی، سیاسی و انتخابات ممنوع و بزه (جرم) شمرده می‌شود.",
                "",
                " بخش ششم: دادگستری مستقل و نهاد دادرس مردمی",
                
                "<b>بند ۱۵: استقلال مطلق دادگری</b>",
                " دادگستری نهادی مستقل است که بودجه، سرپرستی و تشکیلات آن توسط خودِ بدنه دادرسان و شورای عالی دادگری (بدون دست‌اندازی دولت یا شاه) اداره می‌شود. دادرسان در صدور احکام تنها فرمانبردار داد و وجدان خویش هستند و امنیت شغلی آنان تضمین شده است.",
                
                "<b>بند ۱۶: نهاد دادرس مردمی (امبودزمان - برگرفته از حقوق سوئد)</b>",
                " برای جلوگیری از ستم کارگزاران حکومت بر مردم، انجمن نمایندگان ملت، بازرسانی مستقل به نام «دادرس مردمی» می‌گمارد. این نهاد حق دارد به شکایت‌های مردم از دستگاه‌های دولتی، ارتش و شهرداری‌ها رسیدگی کند و کارهای آنان را در دادگاه به چالش بکشد.",
                
                "<b>بند ۱۷: دیوان عالی آیین ریشه‌ای</b>",
                " این دیوان، مرجع نهایی گزارش (تفسیر) آیین ریشه‌ای و سنجش دادهای مصوب انجمن با اصول حقوق بشر، مردم‌سالاری و عدم تمرکز قدرت است. هر شهروندی که حس کند مصوبه‌ای یا کارکردی حقوق اساسی او را زیر پا گذاشته، حق شکایت مستقیم به این دیوان را دارد",
               "",
                "بخش هفتم: اداره خودگردان استان‌ها و توزیع دارایی‌ها",
               
                "<b>بند ۱۸: بخش‌بندی عمودی قدرت (انجمن‌های استانی)</b>",
                " ایران به مرز بوم‌های خودگردان داخلی تقسیم می‌شود. کارهای مربوط به آموزش، فرهنگ بومی، توسعه شهری و روستایی، بهداشت، پلیس محلی و بودجه‌های منطقه‌ای به طور کامل در اختیار «انجمن‌های استانی» و «شوراهای شهر و روستا» که مستقیماً توسط مردم همان مرز و بوم برگزیده می‌شوند، قرار می‌گیرد. پایتخت تنها مسئول سیاست خارجی، دفاع ملی و پول ملی است.",
                
                "<b>بند ۱۹: پخش عادلانه سرمایه ملی</b>",
                " درآمد حاصل از سرچشمه‌های طبیعی کشور دارایی مشترک کل ملت ایران است. با این حال روش توزیع بودجه باید به گونه‌ای تنظیم شود که سهم ویژه‌ای به استان‌های محل استخراج و مناطق محروم تخصیص یابد تا توازن سرزمینی برقرار شود.",
                "",
                " بخش هشتم: توسعه پایدار و پاسداری از زیست‌بوم (هئوروتات و امرتات)",
                
                "<b>بند ۲۰: پایداری آب، خاک و هوا</b>",
                "پاسداری از محیط زیست، پیشگیری از بیابان‌زایی، زنده کردن تالاب‌ها و رودخانه‌ها و صیانت از حیات وحش، از اصول بنیادین فرمانروایی است. هرگونه سیاست صنعتی یا کشاورزی که پایداری زیست‌محیطی ایران را برای نسل‌های آینده به خطر اندازد، ایستاده و باطل اعلام می‌شود",
               
                "<b>بند ۲۱: حق رفاه، کار و آموزش رایگان</b>",
                " دولت مکلف است بستر رفاه همگانی شامل آموزش باکیفیت و رایگان، بهداشت و درمان رایگان و دستگاه تأمین اجتماعی جامع را برای همه شهروندان بدون هیچ‌گونه تبعیض مهیا سازد.",
                "راهنمای سرچشمه‌ها (منابع):",
                "آیین ریشه‌ای - پیش‌نویس قانون اساسی پادشاهی مشروطه ایران",
                "گاتها، سرودهای اهورایی زرتشت؛ پژوهش دکتر خسرو خزاعی",
                "الگوهای برتر برگرفته از حقوق اساسی پادشاهی مشروطه سوئد (قانون اساسی نمادین ۱۹۷۴ و نظام امبودزمان) و بریتانیا (پاسخگویی پارلمانی)."
            ],
            images: ["farva.jpeg", "pasar.jpeg", "bg.jpeg"],
            video: "me1.mp4"
        },
        en: {
            title: "The Grand Charter Page",
            text: [
                "Every web page should have a title to describe its meaning.",
                "The Root Constitution of the Democratic Constitutional Monarchy of Iran",
                " Integration of Constitutionalism, Modern Democracy, and Indigenous Values (Asha, Vohuman, Khshathra)",
                "",
                " Chapter I: Axiological Principles and Foundations of the System",
                "<b>Article 1: Inherent Human Dignity and Freedom of Will</b>",
                "Based on human free will, the dignity, fundamental rights, and liberty of all citizens of Iran are inviolable and inalienable. The ultimate goal of governance is to provide a flourishing environment for the well-being, happiness, and material and spiritual progress (Haurvatat) of all individuals.",
                "<b>Article 2: Source and Essence of National Sovereignty</b>",
                "National sovereignty belongs solely and unconditionally to the nation of Iran, exercised democratically, in a decentralized manner, through the ballot box and elected institutions. No traditional, ideological, hereditary, or military institution has the right to usurp, suspend, or limit national sovereignty.",
                "<b>Article 3: Rule of Law and Truth (Asha)</b>",
                "The law is the manifestation of the collective will and wisdom of the nation. All laws, regulations, and judicial verdicts must align with the principles of truth, science-based justice, the International Bill of Human Rights, and environmental sustainability (Asha). No source or expediency stands above the law.",
                "",
                "Chapter II: Status, Boundaries, and Symbolic Duties of the Constitutional Monarchy (Based on the Swedish Model)",
                "<b>Article 4: Symbolic Nature and Total Separation of the Monarch from Power</b>",
                "Following the constitutional framework of Sweden (The Instrument of Government 1974), the Monarchy is a purely symbolic institution, completely devoid of any political, legislative, executive, or judicial power. The Monarch is the symbol of national unity, historical continuity, and harmony among all ethnicities and segments of Iran (Guardian of Armaiti) and is strictly barred from intervening in sovereign affairs.",
                "<b>Article 5: Removal of Executive Powers and the Nomination of the Prime Minister</b>",
                " In accordance with advanced Scandinavian (Swedish) laws, the Monarch plays no role in appointing military commanders or nominating the Prime Minister. The duty of nominating the Prime Minister and tasking them with forming the government rests entirely with the Speaker of the Parliament (the Speaker of the House of Representatives), who is elected by the people. The signing of laws by the Monarch is a purely ceremonial act, and the Monarch has no right to veto any legislation.",
                "<b>Article 6: Mechanism for Dethronement or Abdication</b>",
                "Should the Monarch violate the boundaries of the Constitution or breach their oath, as determined by the Supreme Court or a two-thirds majority of the Parliament, they shall be automatically dethroned. The Parliament shall then decide on the continuity of the institution, a change of person, or a referendum regarding the structure of the office.",
                "",
                "Chapter III: Fundamental Rights, Liberties, and Citizen Safeguards",
                "<b>Article 7: Comprehensive Equality of Gender, Ethnicity, and Belief</b>",
                " All citizens of Iran, regardless of gender, descent, language, ethnicity, race, philosophical, religious, or political views, or personal orientations, are completely equal before the law. The application of constructive affirmative action in favor of historically marginalized groups to establish true justice is lawful.",
                "<b>Article 8: Inviolability of Conscience (Daena) and the Private Sphere</b>",
                "Conscience, belief, and personal religion are strictly individual and free domains. Inquisition of beliefs and the establishment of an official state religion are prohibited in the Constitution. The residence, correspondence, digital communications, and privacy of citizens are immune from any arbitrary intrusion, wiretapping, or inspection without a clear and substantiated judicial order.",
                "<b>Article 9: Freedom of Expression, Media, and Access to Information</b>",
                "Freedom of thought, expression, press, art, and newspapers is guaranteed. Prior censorship is forbidden. Any monopoly over broadcasting media by the government or the monarchy is illegitimate. All citizens have the right to free and unfiltered access to the flow of information and the global internet.",
                "<b>Article 10: Judicial Security, Prohibition of Torture, and the Presumption of Innocence</b>",
                "Every accused person is presumed innocent until their guilt is proven in a public court, before a jury, and with the right to an independent counsel. Any physical or psychological abuse (torture), coerced confession, prolonged solitary confinement, and degrading treatment are strictly prohibited, and violators shall be prosecuted without any statute of limitations.",
                "",
                "Chapter IV: Structure of Collective Wisdom (The Bicameral Legislative Branch)",
                "<b>Article 11: The House of Representatives (Parliament)</b>",
                " This house is composed of representatives elected through nationwide, free, secret, periodic, and proportional representation elections. The primary duties of this house include enacting ordinary legislation, approving the national budget, confirming the Prime Minister, and overseeing the executive branch.",
                "<b>Article 12: The Senate of Provinces and Experts</b>",
                "This house consists of equal representatives from the provinces and scientific/specialized elites of the country to defend local interests and sustainable development at the macro level. No law shall be finalized without being reviewed by both houses to prevent the centralization of power (Vohuman).",
                "",
                "Chapter V: The Executive Branch and the Servant Government (Khshathra)",
                "<b>Article 13: Formation of the Government and Accountability (UK Constitutional Model)</b>",
                " The head of government is the Prime Minister. The leader of the party or coalition that wins the majority of seats in the House of Representatives shall be tasked with forming the cabinet. The government is fully accountable to the Parliament, and the House of Representatives can dismiss the government or any minister at any time through a vote of no confidence.",
                "<b>Article 14: Control of the Executive Power and the Military</b>",
                " Military, border control, and security forces must remain entirely non-political and non-factional, acting under the direct oversight and command of the civilian government and the Parliament. The intervention of the armed forces in economic, commercial, political, and electoral affairs is strictly prohibited and considered a criminal offense.",
                "",
                "Chapter VI: Independent Judiciary and the Arbiter of Truth (The Court of Asha)","<b></b>",
                "<b>Article 15: Absolute Independence of the Judiciary</b>",
                "The Judiciary is an independent institution whose budget, management, and administration are run by the body of judges themselves and the Supreme Judicial Council, without any interference from the government or the monarch. Judges are subservient only to the law and their own conscience in issuing verdicts, and their tenure security is guaranteed.",
                "<b>Article 16: The Parliamentary Ombudsman (Based on the Swedish Model)</b>",
                "To prevent state officials from oppressing citizens, the House of Representatives shall appoint independent ombudsmen. This office has the right to investigate complaints from citizens against government agencies, the military, and municipalities, and can challenge their actions in court.",
                "<b>Article 17: The Supreme Constitutional Court</b>",
                "This court is the ultimate authority for interpreting the Constitution and assessing the conformity of laws passed by Parliament with human rights, democracy, and the decentralization of power. Any citizen who feels that a piece of legislation or an executive action has violated their fundamental rights has the right to file a direct complaint with this court.",
                "",
                "Chapter VII: Autonomous Administration of Provinces and Distribution of Wealth",
                "<b>Article 18: Vertical Division of Power (Provincial Assemblies)</b>",
                " Iran is divided into self-governing internal regions and provinces. Affairs related to education, local culture, urban and rural development, healthcare, local police, and regional budgets are completely devolved to 'Provincial Assemblies' and 'City and Village Councils' directly elected by the people of those regions. The capital is solely responsible for foreign policy, national defense, and the national currency.",
               "<b>Article 19: Equitable Distribution of National Wealth</b>",
               "Revenue generated from the country's natural resources is the collective property of the entire nation of Iran. Nonetheless, the budget allocation mechanism must be structured in a way that assigns a special share to the producing provinces and underdeveloped regions to ensure regional balance and justice.",
               "",
               "Chapter VIII: Sustainable Development and Environmental Protection (Haurvatat and Ameretat)",
               "<b>Article 20: Sustainability of Water, Soil, and Air</b>",
               "Protecting the environment, preventing desertification, reviving wetlands and rivers, and conserving wildlife are fundamental principles of governance. Any industrial or agricultural policy that jeopardizes the environmental sustainability of Iran for future generations shall be halted and declared null and void.",
                 "<b>Article 21: Right to Welfare, Work, and Free Education</b>",
               "The government is obligated to provide a universal welfare framework, including high-quality free education up to the end of secondary school, free healthcare, and a comprehensive social security system for unemployment, old age, and disability for all citizens without any discrimination.",
                "Sources:",
               "The Root Constitution - Draft Constitution of the Constitutional Monarchy of Iran", 
               "The Gathas, the Sublime Songs of Zarathustra; Research by Dr. Khosro Khazai",
               "Best practices incorporated from the constitutional frameworks of advanced constitutional monarchies, namely Sweden (Instrument of Government 1974 and the Ombudsman system) and the United Kingdom (Parliamentary Accountability)."

                
            ],
            images: ["farva.jpeg", "pasar.jpeg", "bg.jpeg"],
            video: "me1.mp4"
        }
    },
    News: {
        fa: {
            title: "تار برگ خبر",
            text: "به تار برگ خبر خوش آمدید.",
            images: [],
            video: ""
        },
        en: {
            title: "News Page Title",
            text: "Welcome to the News page. News describes how HTML elements are to be displayed on screen.",
            images: [],
            video: ""
        }
    },
    Programs: {
        fa: {
            title: "تار برگ برنامه ها",
            text: ["به تار برگ برنامه ها خوش آمدید. این بخش به صفحات وب قابلیت‌های تعاملی اضافه می‌کند.",
                   "",
                   "برنامه‌های بازگشت به خویشتن فرهمند",
                   "",
                   "نقشه راه بیداری: بازگشت به خویشتن فرهمند و روزگار شکوه درون",
                   "",
                   "فرّ و شکوهِ ایرانی، یک افسانه‌ی فراموش‌شده در کتاب‌ها نیست؛ آتشِ زیر خاکستری است در جان و روانِ تو. وقت آن رسیده است که این گنجِ نهان را آشکار کنی.",
                   "",
                    "در روزگاری که شتابِ جهانِ نو، آدمی را از ریشه‌های خویش جدا کرده است، «برنامه‌های بیداری نسل شیک» طراحی شده‌اند تا تو را به «خویشتنِ فرهمندت» بازگردانند. فرهمندی یعنی رسیدن به آن نیروی تابناک درونی که به اندیشه‌ات روشنایی، به اراده‌ات استواری و به زندگی‌ات شکوه می‌بخشد.",
                    "ما تاریخ را نمی‌خوانیم که در گذشته بمانیم؛ تاریخ را می‌کاویم تا کدهای توانمندی و خودباوری را برای ساختنِ آینده‌ای سرافرازانه برداریم.",
                    "",
                    "برنامه‌های گام‌به‌گام برای شکوفایی توانمندی‌های نهان",
                    "",
                    "۱. کارگاه‌های بیداری فرّ درونی (دوره روان‌شناسی و خرد ایرانی)",
                     "* هدف: پیوند دادن روان‌شناسی روز جهان با الگوهای خردمندانه ایران باستان.",
                    " * آنچه به دست می‌آوری: رهایی از سردرگمی هویتی، دست‌یابی به آرامشِ استوار درونی، و یادگیریِ هنرِ «پادشاهی بر ذهن و رفتار خویشتن».",
                    "",
                    "۲. چالش‌های ۲۱ روزه خویش‌فرمانی (عادت‌سازی به سبک نیاکان)",
                    " * هدف: تبدیل اندیشه و باور به رفتار و دستاوردهای واقعی در زندگی روزمره.",
                     "* آنچه به دست می‌آوری: تمرین‌های روزانه برای تقویتِ انضباط فردی، پاک‌سازی روان از افکارِ ناتوان‌کننده، و تمرینِ گفتار، کردار و پندارِ نیک در دنیای مدرن.",
                    "",
                   " ۳. هم‌اندیشی‌های نسل شیک (نشست‌ها و گفتگوهای هم‌افزا)",
                    " * هدف: گرد هم آمدنِ ایرانیانِ آگاه، هدفمند و پیشرو که به دنبال رشد فردی و اثرگذاری اجتماعی هستند.",
                    " * آنچه به دست می‌آوری: حضور در شبکه‌ای از هم‌فکران، تبادل ایده‌های نوآورانه، و ساختن جامعه‌ای خویش‌باور و پویا.",
                    "",
                    "۴. مربی‌گری اختصاصی: «کشف جام جم درونی»",
                     "* هدف: سنجش دقیق استعدادها و ترسیم نقشه راه اختصاصی زندگی و کسب‌وکار بر پایه توانمندی‌های واقعی تو.",
                     "* آنچه به دست می‌آوری: شفافیت کامل در مسیر شغلی و شخصی، و تبدیل توانِ بالقوه به موفقیت‌های بالفعل و پایدار.",
                     "",
                    " پیمان با خویشتن",
                    " تو تنها بیننده‌ی تاریخ نیستی؛ تو نویسنده‌ی فصلِ بعدیِ این شاهکاری.",
                    " فرهمندی و شکوه، از همین لحظه و با نخستین گامی که برای شناختِ خود برمی‌داری آغاز می‌شود. خویشتنِ بزرگت در انتظارِ توست؛ او را بیدار کن!",
                    ""
                  
                  ],
            images: [],
            video: "",
            vimeoUrl: "https://player.vimeo.com/video/1203474449"
        },
        en: {
            title: " Programs for Awakening the Glorious Self",
            text: ["Welcome to the Programs page.",
                   "",
                   "The Roadmap to Awakening: Reclaiming Your Glorious Self and Inner Splendor",
                   "",
                    "The divine glory (Farrah) and splendor of the Iranian spirit are not forgotten myths locked in ancient books; they are embers beneath the ashes of your soul. The time has come to unveil this hidden treasure.",
                    "In an age where the frantic pace of the modern world has severed humanity from its roots, the Chic Generation Awakening Programs are crafted to guide you back to your, Glorious Self. Divine glory (Farrah) is that luminous inner force that brings clarity to your mind, steadfastness to your will, and majesty to your life.",
                    "We do not explore history to linger in the past; we delve into our heritage to retrieve the blueprints of capability and self-worth, forging a triumphant future.",
                    "",
                    "Step-by-Step Paths to Unlocking Your Hidden Potential",
                    "1. Workshops for Awakening the Inner Glory (Psychology & Ancient Wisdom)",
                    " * Purpose: Blending modern global psychology with the timeless wisdom of ancient Iran.",
                    " * What You Attain: Liberation from identity confusion, an unshakable inner peace, and mastery over the art of governing your own mind and conduct.",
                    "",
                   "2. 21-Day Self-Mastery Challenges (Habit-Building in the Spirit of the Ancestors)",
                     "* Purpose: Translating noble thoughts and beliefs into tangible actions and real-world achievements.",
                     "* What You Attain: Daily practices to strengthen personal discipline, cleanse the mind of limiting thoughts, and live out good thoughts, good words, and good deeds in the modern world.",
                    "",
                   "3. The Chic Generation Conclaves (Synergistic Gatherings & Dialogues)",
                     "* Purpose: Uniting conscious, purpose-driven, and forward-thinking individuals striving for personal growth and social impact.",
                     "* What You Attain: A place within a network of like-minded peers, the exchange of innovative ideas, and the building of a self-reliant, dynamic community.",
                   "",
                   "4. One-on-One Mentorship: Discovering the Cup of Jamshid Within",
                     "* Purpose: Precise assessment of your talents and crafting a personalized roadmap for your life and career based on your true capabilities.",
                    " * What You Attain: Absolute clarity in your professional and personal trajectory, converting potential energy into lasting, real-world success.",
                   "",
                   " A Covenant with Oneself",
                    " You are not merely a spectator of history; you are the author of its next glorious chapter.",
                    " Splendor and inner glory begin this very moment, with the first step you take toward self-awareness. Your greater self awaits—awaken it!"
                  ],
            images: [],
            video: "",
            vimeoUrl: "https://player.vimeo.com/video/1203474449"
        }
    },
    Hist: {
        fa: {
            title: "تار برگ تاریخ",
            text: ["به تار برگ تاریخ خوش آمدید. این بخش به صفحات وب قابلیت‌های تعاملی اضافه می‌کند. هرگز از یاد نمیبریم.",
                  "سرآغاز: سرگذشت پیشدادیان",
                   "فرنام بنیادین:",
                    "سرآغاز روشنایی و خرد؛ داستانی که از ریشه‌های تو می‌گوید",
                    "سرگذشت ما با جنگ آغاز نشد؛ با «آگاهی»، «سازندگی» و «پادشاهی بر خویشتن» آغاز شد.",
                    "بخش نخست: پیشدادیان؛ نخستین دادگستران و سازندگان جهان",
                    "داستان ما از جایی آغاز می‌شود که تاریکی و نادانی جهان را فراگرفته بود. پیشدادیان (نخستین دادگستران) آمدند تا به آدمی یاد بدهند که چگونه از هیچ، همه‌چیز بسازد.",
                    "آنان کسانی بودند که:",
                     "* آتش را نه برای ویرانی، بلکه برای گرمی و روشنایی پیدا کردند (هووشنگ).",
                     "* دبیره و نوشتن را برای رساندن دانش و خرد رام کردند (طهمورث دیوبند).",
                    "تو از تباری هستی که نخستین بار جهان را ساخت. خواستِ پیشدادیان در خون توست؛ تو برای گردن‌نهادن در برابر تاریکی‌ها ساخته نشده‌ای، تو ساخته شده‌ای تا مانند نیاکانت، روشنایی را بیافرینی.",
                    
                    "بخش دوم: روزگار جمشید؛ بالندگی خرد و جام جم درون",
                    "روزی که جمشید بر تخت نشست، روزگار زرین ایران آغاز شد. او نه با نیروی تیغ، بلکه با پزشکی، ساخت‌وساز، هنر، و جهانداری خردمندانه، بیماری، پیری و تهیدستی را از سرزمین راند. نوروز، یادگار آن جهش بزرگ اندیشه‌ای است.",
                    "جام جمشید (جام جم) چیزی جز «روانِ آگاه و آینه‌ی خودشناسی» نبود؛ ابزاری که با آن می‌شد رازهای جهان را دید.",
                    "اما جمشید یک آموزه بزرگ هم برای ما داشت: وقتی خودبینی بر خرد چیره شود، شکوه رخ برمی‌تابد.",
                    " ",
                    " جام جم در دست‌های توست. «جام جم» همان توان اندیشه و توانمندی‌های نهان توست که اگر با فروتنی و خودآگاهی همراه شود، می‌توانی روزگار زرین زندگی خودت را پی‌ریزی کنی.",
                    "", 
                    "بخش سوم: فریدون، ایرج و تور؛ نبرد بزرگ گزینش‌ها",
                    "پس از تاریکی ضحاک، فریدون نشانِ دادگری و رهایی شد. اما بزرگ‌ترین آزمون سرگذشت در نژاد او شکل گرفت: بخش‌کردن جهان میان ۳ پسرش؛ سلم، تور و ایرج.",
                     "* تور و سلم: نشانِ خشم، آز، زیاده‌خواهی و رشک‌ورزی بودند.",
                     "* ایرج: نشانِ خرد، آشتی، بزرگواریِ آدمی و گوهر اصیل بود.",
                    "ایرج جان‌باخته‌ی کینه شد، اما نام و نژادش تا جاوید نشانِ آبرو و گوهر اصیل ایرانی باقی ماند. از دل این رنج، پهلوانانی چون منوچهر و رستم زاده شدند تا نشان دهند راستی و داد هرگز خاموش نمی‌شود.",
                     " ",
                    " درون هر یک از ما نبردی میان «تور» (آز و خشم درونی) و «ایرج» (خرد و گوهر اصیل) در برپاست. سرگذشت ایران به تو یاد می‌دهد که گزینشِ «راه ایرج» یعنی گزینشِ سرترازی و آبرو، و این تنها راهی است که تو را به پهلوانِ داستانِ زندگی خودت دگرگون می‌سازد.",
                    " ",
                    "پایان‌سخن و فراخوان به کار:",
                    " تو یادگاردار این شاهکاری!",
                    " داستان پیشدادیان، افسانه‌های کهنه نیستند؛ این‌ها بن‌مایه‌هایِ باورداری و توانستن در جان و روانِ تو هستند.",
                    " اکنون نوبت توست که در روزگار نو، پیشدادیِ درون خودت را بیدار کنی. خرد جمشید، آزاده‌گی ایرج و خواستِ فریدون را بردار و آینده‌ات را بساز.",
                    " [ کلید: آشکارسازیِ توانمندی‌های درون / درآمدن به بخش خودشناسی ]",
                    " ",
                  ],
            images: [],
            video: "",
            vimeoUrl: "https://player.vimeo.com/video/1203474449"
        },
        en: {
            title: "History Page Title",
            text: ["Welcome to the History page. History makes you be aware of yourself and know about others. we never forget",
                   "The Dawn of Light and Wisdom: A Tale of Your Roots",
                    "Our history did not begin with conquest; it began with awareness, creation, and mastery over oneself.",
                    "Part I: The Pishdadians — The First Lawgivers and Builders of the World",
                    "Our story unfolds when darkness and ignorance enveloped the earth. The Pishdadians (the First Lawgivers) arose to teach humanity how to shape everything out of nothing.",
                    "They were the ones who:",
                     "* Discovered fire not for destruction, but for warmth and illumination (Houshang).",
                     "* Mastered script and writing to pass on knowledge and wisdom (Tahmuras).",
                    "",
                    " You descend from a lineage that built the world for the first time. The resolve of the Pishdadians flows in your veins; you were not forged to yield to darkness—you were forged to create light, just as your ancestors did.",
                    "",
                    "Part II: The Age of Jamshid — The Flourishing of Wisdom and the Cup Within",
                    "When Jamshid ascended the throne, the Golden Age of Iran dawned. Not through the blade of a sword, but through medicine, architecture, art, and wise governance, he banished sickness, aging, and hardship from the land. Nowruz stands as a lasting legacy of that great leap in human thought.",
                    "The Cup of Jamshid (Jam-e Jam) was nothing less than the (conscious soul and the mirror of self-awareness—)a vessel through which one could perceive the mysteries of existence.",
                    "Yet Jamshid left us a monumental lesson: When hubris triumphs over wisdom, glory slips away.",
                    "",
                    " The Cup of Jamshid is already in your hands. It represents your power of thought and your hidden potential. When paired with humility and self-awareness, you can build the Golden Age of your own life.",
                    "", 
                    "Part III: Fereydoun, Iraj, and Tur — The Great War of Choices",
                    "Following the darkness of Zahhak, Fereydoun became the symbol of justice and liberation. Yet the greatest test in history emerged within his own bloodline: the dividing of the realm among his three sons—Salm, Tur, and Iraj.",
                     "* Tur and Salm: Embodied wrath, greed, excess, and envy.",
                     "* Iraj: Embodied wisdom, peace, human dignity, and pure nobility.",
                    "Iraj fell victim to malice, yet his name and lineage remained an eternal beacon of honor and noble spirit. From the depths of this grief, heroes such as Manuchehr and Rostam were born, proving that truth and justice are never extinguished.",
                    "",
                    " Within each of us, a battle rages between Tur (inner greed and wrath) and Iraj (wisdom and noble character). History teaches you that choosing the Path of Iraj, means choosing dignity and honor—and that is the sole path that transforms you into the hero of your own life story.",
                    "", 
                    " Closing Word and Call to Action:",
                    " You are the Guardian of This Masterpiece!",
                    " The stories of the Pishdadians are not ancient myths; they are the fundamental blueprints of belief and capability within your spirit.",
                    " Now it is your turn to awaken the Pishdadian within yourself in this modern era. Harness the wisdom of Jamshid, the noble freedom of Iraj, and the resolve of Fereydoun to forge your future.",
                    " [ Button: Unlock Your Inner Potential / Enter the Journey of Self-Discovery ]",
                    ""    
                  ],
            images: [],
            video: "",
            vimeoUrl: "https://player.vimeo.com/video/1203474449"
        }
    },
    // Dropdown items can live here too!
    tutorials: {
        fa: { title: "تار برگ اصلی آموزش‌ها", text: "به مرکز آموزش‌های ما خوش آمدید. در این بخش می‌توانید آموزش‌های مختلف را پیدا کنید." },
        en: { title: "Tutorials Home", text: "Welcome to our Tutorials center. Here you can find various educational topics." }
    },
    References: {
        fa: { title: "مراجع", text: "به مرکز آموزش‌های ما خوش آمدید. در این بخش می‌توانید مراجع مختلف را پیدا کنید." },
        en: { title: "References Home", text: "Welcome to our references page. Here you can find all documentations and resources." }
    },
    Examples: {
        fa: { title: "نمونه ها", text: "به مرکز آموزش‌های ما خوش آمدید. در این بخش می‌توانید مراجع مختلف را پیدا کنید." 
        },
        en: { title: "Example Home", text: "Welcome to our references page. Here you can find all documentations and resources." }
    },
    contact: {
        fa: { title: "پیوند با ما", text: "به مرکز آموزش‌های ما خوش آمدید. در این بخش می‌توانید مراجع مختلف را بفرستید.",
            isContactPage: true
         },
        en: { title: "Contact us", text: "Welcome to our contact. Here you can upload all documentations and resources.",
            isContactPage: true
         }
    }

};
