const pageDatabase = {
    Methods: {
        fa: {
            title: "  رویه نخست: تار برگ نسل شیک پاسارگادی",
            text: [
            "به تاربرگِ «نسلِ شیکِ پاسارگادی» خوش آمدید؛ جایی که شکوه و شکوهمندیِ ریشه‌های دیرین و کهن‌دیارِ ما با خرد، دانش و اندیشه‌ی بیدارِ امروز پیوند می‌خورد.",
            "این پایگاه، نه تنها یک رسانه‌ی ساده، بلکه بستری برای بیداریِ بزرگِ روان، اندیشه، و خودباوریِ هر ایرانیِ سرافراز است.",
            "آرمانِ بنیادینِ ما تنها بازخوانیِ گذشته و نگریستن به دیروز نیست، بلکه برون‌کشیدنِ بن‌مایه‌های توانمندی، منشِ والایی و فرّ درونیِ آدمیِ ایرانی است؛",
            "تا دوباره به یاد آوریم که ما هرگز برای زیستن در سایه‌ی نومیدی، خستگی، سستی و خوی گرفتن به چگونگی‌های ناخواسته ساخته نشده‌ایم،",
            "بلکه یادگاردارانِ راستینِ خرد، فرزانگی، سازندگی و ارجمندیِ آدمی بر روی زمین هستیم.",
            "گاهی در خستگی‌ها و گرفتاری‌های هرروزه، ناخودآگاه، خوی‌ها و رفتارهایی چون گردن‌نهادن، ناامیدی و فراموشیِ شایستگی‌های خویشتن بر روانِ ما سایه می‌افکنند و توانِ پویایی را می‌گیرند.",
            "اما بیداریِ راستین از همان دمی آغاز می‌شود که ارج‌ها و گوهرهای درونی‌مان را دوباره به یاد آوریم و خویشتنِ خویش را بازیابیم.",
            "«تاربرگِ آیین» نخستین گام در این راهِ پرفروغ است؛",
            "تلاشی خستگی‌ناپذیر برای بازشناختِ شهرآینی، دادگری، راستی و آزادی بر پایه‌ی والاییِ سرشتِ آدمیِ ایرانی—",
            "سرمشق‌هایی گران‌سنگ که روزگاری کیستی و تبارِ ما را در سراسرِ جهان پرآوازه و والاتبار ساختند",
            "و امروز نیز یگانه چاره‌ساز و راهگشا برای ساختنِ آینده‌ای سرافراز، آباد، آزاد و شایسته برای فرزندان و نسل‌های فردای این مرزوبوم هستند.",
            "ما در این راه، دستِ همکاری و همبستگی به سوی هر ایرانیِ بیدار و خردمند دراز می‌کنیم تا با هم، فرّ دیرین را به زندگیِ امروز بازگردانیم.",
            "این بیداریِ فرخنده، نه یک آرزوی دوردست، بلکه برنامه‌ای روزانه برای پرورشِ منش، منشوری برای توانمندسازیِ اندیشه و رفتاری شایسته است.",
            "ما بر آنیم تا با تکیه بر دانشِ امروزی و هوشمندی، ابزارهای نوینی برای رشدِ فردی و اجتماعیِ نسلِ جوانِ ایران‌زمین فراهم آوریم.",
            "زیرا باور داریم که بازسازیِ میهن، از بازسازیِ روان و خودباوریِ تک‌تکِ فرزندانِ این سرزمین آغاز می‌شود.",
            "هر گامِ کوچک در راهِ خودآگاهی و افراشتنِ پرچمِ خردورزی، روزنه‌ای روشن به سوی رهایی از تاریکی و رسیدن به بامِ دادگری است.",
            "شما با پیوستن به این جنبشِ فرهنگی و اندیشه‌ای، سهمی بزرگ در نگارشِ فصلِ تازه‌ی تاریخِ پرشکوهِ این دیار خواهید داشت.",
            "پیمان می‌بندیم که تا رسیدن به فرداهای روشن و روزگارِ شایسته‌ی ایران، استوار و خستگی‌ناپذیر در کنارِ هم گام برداریم."    
            
            ],
             articles:[
                {
                id: "article1",
                title: " به تار برگ آیین خوش آمدید.",
                summary: "این پیش‌نویسِ آیینِ ریشه‌ای، برای برپاییِ شهریاریِ پیمان‌بنیاد و مردم‌سالاریِ ناب در ایران، با الگوبرداری از کشورهای پیشرفته و آمیزشِ آن با ارزش‌های بومی، شاه را نهادی یکسره نمادین می‌سازد و توانِ فرمانروایی را یکسر به انجمنِ نمایندگانِ ملت، دولتِ پاسخگو، دادگستریِ مستقل و استان‌های خودگردان می‌سپارد.",
                fullText:[
                "برای نزدیک‌تر کردن این پیش‌نویس به کشورهای پادشاهی مشروطه‌ی پیشرفته و مدرن (مانند سوئد، نروژ و بریتانیا)، چند ابزار حقوقی و عملی به متن افزوده شده است:",
                "",
                "۱. مدل پادشاهی سوئد (قانون اساسی ۱۹۷۴): در سوئد، پادشاه حتی دیگر نخست‌وزیر را رسماً معرفی نمی‌کند و این خویشکاری بر عهده سالار انجمن (رئیس پارلمان) است. این بالاترین سطح تفکیک قدرت برای جلوگیری از تمرکز قدرت در دست یک تن است.",
                "۲. مکانیسم دادرس مردمی (Ombudsman): برآمده از حقوق مدرن اسکانیا (سوئد) برای نظارت مستقیم مردم بر کارکرد دستگاه‌های دولتی.",
                "۳. سیستم پادشاهی بریتانیا: تمرکز بر سنت‌های پارلمانی و پاسخگویی تام کارگزاران اجرایی.",
                "در ادامه، متن کامل بازنویسی‌شده با واژگان سره و ذکر سرچشمه‌ها (شامل کشورهای پیشرفته) آمده است:",
                " آیین ریشه‌ای شاهنشاهی مشروطه مردم‌سالار ایران",
                " آمیزش ساختار مشروطه، مردم‌سالاری امروزی، الگوهای اسکانیا (سوئد) و ارزش‌های بوم‌آور",
               "",
                " بخش نخست: پایه‌های ارزشی و بنیادهای دستگاه",
               "",
                "<b>بند ۱:  والاییِ سرشت انسان و آزادی خواست</b>",
                "   بر پایه خرد آزاد انسان، والایی، حقوق بنیادین و آزادیِ خواستِ (اراده) همه شهروندان ایران، گزندناپذیر و سلب‌نشدنی است. آرمانِ غاییِ فرمانروایی، فراهم آوردن بستری شکوفا برای بهزیستی، شادی و رشد مادی و مینوی (هئوروتات) همگان است.",
                
                "<b>بند ۲: سرچشمه و درون‌مایه فرمانروایی ملی</b>",
                "   فرمانروایی، تنها و بی‌هیچ قید و شرطی از آنِ ملت ایران است که به شیوه مردم‌سالار، بخش‌بخش‌شده (غیرمتمرکز) و از راه صندوق رای و نهادهای انتخابی به کار بسته می‌شود. هیچ نهاد سنتی، باورمدار، موروثی یا ارتشی، حق غصب، ایست یا محدود کردن فرمانروایی ملی را ندارد.",
               
                "<b>بند ۳: فرمانروایی داد و راستی (اشا)</b>",
                " داد (قانون)، نمود خواست و خردِ همگانی ملت است. همه دادها، آیین‌نامه‌ها و داوری‌های دادگاه‌ها باید هماهنگ با اصول راستی، دادگریِ دانش‌محور، پیمان‌نامه جهانی حقوق بشر و پایداری زیست‌بوم (اشا) باشند. هیچ سرچشمه یا مصلحتی فراتر از داد نیست",
                "",
                "## بخش دوم: جایگاه، مرزها و خویشکاری‌های نمادین شاهنشاهی مشروطه (بر پایه الگوی پادشاهی سوئد)",
                
                "<b>بند ۴: ماهیت نمادین و جدایی تام شاه از قدرت</b>",
                "   بر پایه الگوی ساختار مشروطه سوئد (ریگسداگ ۱۹۷۴)، شاهنشاهی مشروطه، نهادی است سراپا نمادین و بی‌بهره از هرگونه نیروی سیاسی، دادگذاری، اجرایی و داوری. شاه نماد همبستگی ملی، پیوستگی تاریخی و دوستی میان همه تبارها و توده‌های ایران (پاسدار آرمَیْتی) است و از هرگونه دخالت در امور حاکمیتی بازداشته می‌شود.",
               
                "<b>بند ۵: حذف اختیارات اجرایی و معرفی نخست‌وزیر</b>",
                "   به پیروی از دادهای پیشرفته اسکانیا (سوئد)، شاه هیچ نقشی در گماشتن فرماندهان ارتشی یا معرفی نخست‌وزیر ندارد. خویشکاری معرفی نخست‌وزیر و مأمور تشکیل دولت، سراپا بر عهده «سالار انجمن نمایندگان» (رئیس پارلمان) است که برآمده از رأی مردم است. دستینه (امضا) کردن دادها از سوی شاه نیز تنها کاری تشریفاتی است و او حق وازدن (وتوی) هیچ دادی را ندارد.",
               
                "<b>بند ۶: چگونگی برکناری یا کناره‌گیری شاه</b>",
                "در صورتی که شاه به داوریِ دیوان عالی کشور یا رای دو سوم هموندانِ (اعضای) انجمن، از مرزهای آیین ریشه‌ای فراتر رود یا سوگند خود را بشکند، خودبه‌خود برکنار می‌شود. سپس انجمن درباره تداوم، دگرگونی شخص یا همه‌پرسیِ ساختارِ نهاد تصمیم می‌گیرد.",
               "",
                " بخش سوم: حقوق بنیادین، آزادی‌ها و زنهارنامه‌های شهروندی",
               
                "<b>بند ۷: برابری فراگیر زن و مرد، تبارها و باورها</b>",
                "همه شهروندان ایران، چه زن و چه مرد، فارغ از تبار، زبان، قومیت، نژاد، نگرش‌های فلسفی، باوری، سیاسی یا گرایش‌های فردی، در برابر داد کاملاً برابرند. اعمال هرگونه برتری‌دهیِ سازنده به سود گروه‌های به حاشیه رانده‌شده تاریخی برای برقراری دادگری راستین، دادین (قانونی) است.",
                
                "<b>بند ۸: گزندناپذیری وجدان (دَئِنا) و سراچه خصوصی</b>",
                " وجدان، باور و دینِ کسان، قلمرویی کاملاً فردی و آزاد است. تفتیش عقاید و داشتن دین رسمی در آیین ریشه‌ای ممنوع است. خانه، نامه‌نگاری‌ها، پیوندهای رایانه‌ای (دیجیتال) و حریم شخصی شهروندان از هرگونه تاخت‌وتاز، شنود و بازرسی خودسرانه بدون دستورِ روشن و مستدلِ دادگستری مصون است.",
               
                "<b>بند ۹: آزادی بیان، رسانه و دسترسی به آگاهی‌ها</b>",
                "  آزادی اندیشه، بیان، چاپ، هنر و روزنامه‌ها تضمین می‌شود. مهار و سانسور پیش از انتشار ممنوع است. انحصار رسانه‌های شنیداری و دیداری در دست دولت یا نهاد شاهنشاهی نامشروع است. همه شهروندان حق دسترسی آزاد و بدون فیلتر به جریان آزاد آگاهی‌ها و تارنمای (اینترنت) جهانی را دارند.",
                
                "<b>بند ۱۰: امنیت دادگاهی، منع شکنجه و اصل بی‌گناهی</b>",
                "هر متهمی بی‌گناه انگاشته می‌شود مگر اینکه بزهکاری او در دادگاهی علنی، با حضور هیئت منصفه و با حق داشتن وکیل مستقل پایدار شود. هرگونه آزار جسمی یا روانی (شکنجه)، به اقرار واداشتن، زندان انفرادی درازمدت و رفتارهای ضدانسانی مطلقاً ممنوع است و آسیب‌رسانان بدون شمول مرور زمان بازخواست می‌شوند.",
               "",
                "بخش چهارم: ساختار خرد جمعی (دستگاه دادگذاری دو انجمنی)",
                
                "<b>بند ۱۱: انجمن نمایندگان ملت</b>",
                "این انجمن از نمایندگان برگزیده مردم از راه انتخابات سراسری، آزاد، پنهان، دوره‌ای و بر پایه روش تناسبی پدید می‌آید. خویشکاری اصلی این انجمن، وضع دادهای معمولی، تصویب بودجه کشور، رای استوار به نخست‌وزیر و نظارت بر ارکان دولت است.",
                
                "<b>بند ۱۲: انجمن سنای استانی و کارشناسی</b>",
                " این انجمن از نمایندگان برابرِ استان‌ها و نخبگان علمی/تخصصی کشور تشکیل می‌شود تا از منافع بومی و توسعه پایدار استان‌ها در سطح کلان پدافند کند. هیچ دادی بدون بررسی در هر دو انجمن به تصویب نهایی نمی‌رسد تا از تمرکز قدرت جلوگیری شود (وهومن).",
               "",
                "بخش پنجم: دستگاه اجرایی و دولت خادم (خْشَثرَ)",
                
                "<b>بند ۱۳: چگونگی پدید آمدن دولت و پاسخگویی (الگوی مشروطه بریتانیا)</b>",
                "سالار دولت، نخست‌وزیر است. راهبر حزب یا ائتلافی که بیشترین کرسی‌های انجمن نمایندگان را به دست آورد، مأمور پدید آوردن کابینه می‌شود. دولت تماماً در برابر انجمن پاسخگو است و انجمن نمایندگان می‌تواند در هر زمان با رای عدم اعتماد، دولت یا هر یک از وزیران را برکنار کند.",
                
                "<b>بند ۱۴: مهار نیروی اجرایی و ارتش</b>",
                "نیروهای ارتشی، مرزبانی و امنیتی باید کاملاً غیرسیاسی، غیرجناحی و تحت نظارت و فرمان مستقیم دولت غیرارتشی و انجمن عمل کنند. دست‌اندازی نیروهای مسلح در کارهای اقتصادی، بازرگانی، سیاسی و انتخابات ممنوع و بزه (جرم) شمرده می‌شود.",
                "",
                " بخش ششم: دادگستری مستقل و نهاد دادرس مردمی",
                
                "<b>بند ۱۵: استقلال مطلق دادگری</b>",
                " دادگستری نهادی مستقل است که بودجه، سرپرستی و تشکیلات آن توسط خودِ بدنه دادرسان و شورای عالی دادگری (بدون دست‌اندازی دولت یا شاه) اداره می‌شود. دادرسان در صدور احکام تنها فرمانبردار داد و وجدان خویش هستند و امنیت شغلی آنان تضمین شده است.",
                
                "<b>بند ۱۶: نهاد دادرس مردمی (امبودزمان - برگرفته از حقوق سوئد)</b>",
                " برای جلوگیری از ستم کارگزاران حکومت بر مردم، انجمن نمایندگان ملت، بازرسانی مستقل به نام «دادرس مردمی» می‌گمارد. این نهاد حق دارد به شکایت‌های مردم از دستگاه‌های دولتی، ارتش و شهرداری‌ها رسیدگی کند و کارهای آنان را در دادگاه به چالش بکشد.",
                
                "<b>بند ۱۷: دیوان عالی آیین ریشه‌ای</b>",
                " این دیوان، مرجع نهایی گزارش (تفسیر) آیین ریشه‌ای و سنجش دادهای مصوب انجمن با اصول حقوق بشر، مردم‌سالاری و عدم تمرکز قدرت است. هر شهروندی که حس کند مصوبه‌ای یا کارکردی حقوق اساسی او را زیر پا گذاشته، حق شکایت مستقیم به این دیوان را دارد",
               "",
                "بخش هفتم: اداره خودگردان استان‌ها و توزیع دارایی‌ها",
               
                "<b>بند ۱۸: بخش‌بندی عمودی قدرت (انجمن‌های استانی)</b>",
                " ایران به مرز بوم‌های خودگردان داخلی تقسیم می‌شود. کارهای مربوط به آموزش، فرهنگ بومی، توسعه شهری و روستایی، بهداشت، پلیس محلی و بودجه‌های منطقه‌ای به طور کامل در اختیار «انجمن‌های استانی» و «شوراهای شهر و روستا» که مستقیماً توسط مردم همان مرز و بوم برگزیده می‌شوند، قرار می‌گیرد. پایتخت تنها مسئول سیاست خارجی، دفاع ملی و پول ملی است.",
                
                "<b>بند ۱۹: پخش عادلانه سرمایه ملی</b>",
                " درآمد حاصل از سرچشمه‌های طبیعی کشور دارایی مشترک کل ملت ایران است. با این حال روش توزیع بودجه باید به گونه‌ای تنظیم شود که سهم ویژه‌ای به استان‌های محل استخراج و مناطق محروم تخصیص یابد تا توازن سرزمینی برقرار شود.",
                "",
                " بخش هشتم: توسعه پایدار و پاسداری از زیست‌بوم (هئوروتات و امرتات)",
                
                "<b>بند ۲۰: پایداری آب، خاک و هوا</b>",
                "پاسداری از محیط زیست، پیشگیری از بیابان‌زایی، زنده کردن تالاب‌ها و رودخانه‌ها و صیانت از حیات وحش، از اصول بنیادین فرمانروایی است. هرگونه سیاست صنعتی یا کشاورزی که پایداری زیست‌محیطی ایران را برای نسل‌های آینده به خطر اندازد، ایستاده و باطل اعلام می‌شود",
               
                "<b>بند ۲۱: حق رفاه، کار و آموزش رایگان</b>",
                " دولت مکلف است بستر رفاه همگانی شامل آموزش باکیفیت و رایگان، بهداشت و درمان رایگان و دستگاه تأمین اجتماعی جامع را برای همه شهروندان بدون هیچ‌گونه تبعیض مهیا سازد.",
                "راهنمای سرچشمه‌ها (منابع):",
                "آیین ریشه‌ای - پیش‌نویس قانون اساسی پادشاهی مشروطه ایران",
                "گاتها، سرودهای اهورایی زرتشت؛ پژوهش دکتر خسرو خزاعی",
                "الگوهای برتر برگرفته از حقوق اساسی پادشاهی مشروطه سوئد (قانون اساسی نمادین ۱۹۷۴ و نظام امبودزمان) و بریتانیا (پاسخگویی پارلمانی)."
                ],
                articles:[
                    {
                        id: "article1-1",
                        title: "زیر مقاله نخست ",
                        summary: "خلاصه کوتاه خبر اینجا قرار میگیرد...",
                        fullText:"اینجا قرار میگیرد متن کامل مقاله "
                    },
                    {
                        id: "article1-2",
                        title: "زیر مقاله دوم",
                        summary: "خلاصه کوتاه خبر اینجا قرار میگیرد...",
                        fullText:"اینجا قرار میگیرد متن کامل مقاله "
                    },
                    {
                        id: "article1-3",
                        title: "زیر مقاله سوم",
                        summary: "خلاصه کوتاه خبر اینجا قرار میگیرد...",
                        fullText:"اینجا قرار میگیرد متن کامل مقاله "
                    }
                ],
                image: "pahlavi.jpg"
                },
                {
                id: "article2",
                title: "مقاله دوم",
                summary: "خلاصه کوتاه خبر اینجا قرار میگیرد...",
                images: ["bg.jpeg", "pahlavi.jpg","Darius.jpg" ],
                fullText:[
                    "بلکه یادگاردارانِ راستینِ خرد، فرزانگی، سازندگی و ارجمندیِ آدمی بر روی زمین هستیم.",
            "گاهی در خستگی‌ها و گرفتاری‌های هرروزه، ناخودآگاه، خوی‌ها و رفتارهایی چون گردن‌نهادن، ناامیدی و فراموشیِ شایستگی‌های خویشتن بر روانِ ما سایه می‌افکنند و توانِ پویایی را می‌گیرند.",
            "اما بیداریِ راستین از همان دمی آغاز می‌شود که ارج‌ها و گوهرهای درونی‌مان را دوباره به یاد آوریم و خویشتنِ خویش را بازیابیم.",
            "«تاربرگِ آیین» نخستین گام در این راهِ پرفروغ است؛",
            "تلاشی خستگی‌ناپذیر برای بازشناختِ شهرآینی، دادگری، راستی و آزادی بر پایه‌ی والاییِ سرشتِ آدمیِ ایرانی—",
            "سرمشق‌هایی گران‌سنگ که روزگاری کیستی و تبارِ ما را در سراسرِ جهان پرآوازه و والاتبار ساختند",
            "و امروز نیز یگانه چاره‌ساز و راهگشا برای ساختنِ آینده‌ای سرافراز، آباد، آزاد و شایسته برای فرزندان و نسل‌های فردای این مرزوبوم هستند.",
            "ما در این راه، دستِ همکاری و همبستگی به سوی هر ایرانیِ بیدار و خردمند دراز می‌کنیم تا با هم، فرّ دیرین را به زندگیِ امروز بازگردانیم.",
            "این بیداریِ فرخنده، نه یک آرزوی دوردست، بلکه برنامه‌ای روزانه برای پرورشِ منش، منشوری برای توانمندسازیِ اندیشه و رفتاری شایسته است.",
            "ما بر آنیم تا با تکیه بر دانشِ امروزی و هوشمندی، ابزارهای نوینی برای رشدِ فردی و اجتماعیِ نسلِ جوانِ ایران‌زمین فراهم آوریم.",
            "زیرا باور داریم که بازسازیِ میهن، از بازسازیِ روان و خودباوریِ تک‌تکِ فرزندانِ این سرزمین آغاز می‌شود.",
            "هر گامِ کوچک در راهِ خودآگاهی و افراشتنِ پرچمِ خردورزی، روزنه‌ای روشن به سوی رهایی از تاریکی و رسیدن به بامِ دادگری است.",
            "شما با پیوستن به این جنبشِ فرهنگی و اندیشه‌ای، سهمی بزرگ در نگارشِ فصلِ تازه‌ی تاریخِ پرشکوهِ این دیار خواهید داشت.",
            "پیمان می‌بندیم که تا رسیدن به فرداهای روشن و روزگارِ شایسته‌ی ایران، استوار و خستگی‌ناپذیر در کنارِ هم گام برداریم."    
            
                ]
                
                
                
               
                },
                {
                id: "article3",
                title: "مقاله سوم",
                summary: "خلاصه کوتاه خبر اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله ",
                image: "kourosh.jpg"
                },
                {
                id: "article4",
                title: "مقاله چهارم",
                summary: "خلاصه کوتاه خبر اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله ",
                image: "gard.jpg"
                },
                {
                id: "article5",
                title: "مقاله پنجم",
                summary: "خلاصه کوتاه خبر اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله ",
                image: "Darius.jpg"
                },
                {
                id: "article6",
                title: "مقاله ششم",
                summary: "خلاصه کوتاه خبر اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله ",
                image: "darius-egypt.jpg"
                }
            ],
            images: ["farva.jpeg", "pasar.jpeg", "bg.jpeg"],
            video: "me1.mp4"
        },
        en: {
            title: "Page One: The Chic Pasargadae Generation Portal ",
            text: [

                
"Welcome to the 'Chic Pasargadae Generation' portal, where the grandeur of our ancient roots meets the enlightened wisdom of today.",
"This platform is more than just a media outlet; it is a launchpad for a grand awakening of the spirit, mind, and self-belief within every Iranian.",
"Our core purpose is not merely to gaze into the past, but to awaken the innate power, noble character, and inner glory of the Iranian soul;",
"To remind ourselves that we were never created to live in the shadows of despair, fatigue, or passive surrender,",
"But rather as the true guardians of wisdom, nobility, creation, and human dignity on Earth.",
"amid the strain of daily life, habits of submission, hopelessness, and forgetfulness of our worth can cloud our spirit.",
"Yet true awakening begins the very moment we reclaim our inner values and rediscover our true selves.",
"The 'Principles Portal' marks the vital first step on this luminous path;",
"An unyielding effort to rediscover civilization, justice, truth, and freedom based on the supreme dignity of the human spirit—",
"Timeless ideals that once made our heritage legendary throughout the world,",
"And today remain our only clear blueprint to forge a proud, prosperous, and free future for coming generations.",
"In this pursuit, we extend our hands in unity to every awake and thoughtful Iranian to restore our ancient brilliance into modern life.",
"This glorious awakening is no distant dream, but a daily practice to cultivate character and empower the mind.",
"We are devoted to harnessing modern knowledge to build new avenues for the personal and collective growth of our youth.",
"For we firmly believe that rebuilding our homeland begins with rebuilding the spirit and self-worth of every single child of this land.",
"Every small step toward self-awareness and wisdom opens a bright window away from darkness and toward true justice.",
"By joining this cultural movement, you play a vital role in writing the next magnificent chapter of our nation's history.",
"We pledge to walk side by side, steadfast and tireless, until we reach the glorious future our land truly deserves.",
                ""
                
                
            ],
            articles:[
                {
                id: "article1",
                title: "The Grand Charter Page",
                summary: "To establish covenant-bound monarchy and pure democracy in Iran, this draft foundational constitution draws upon advanced nations while fusing them with native values; it renders the Crown entirely symbolic, entrusting sovereign authority wholly to the Nation's Assembly of Representatives, an accountable government, an independent judiciary, and self-governing provinces.",
                fullText:[
                "The Root Constitution of the Democratic Constitutional Monarchy of Iran",
                " Integration of Constitutionalism, Modern Democracy, and Indigenous Values (Asha, Vohuman, Khshathra)",
                "",
                " Chapter I: Axiological Principles and Foundations of the System",
                "<b>Article 1: Inherent Human Dignity and Freedom of Will</b>",
                "Based on human free will, the dignity, fundamental rights, and liberty of all citizens of Iran are inviolable and inalienable. The ultimate goal of governance is to provide a flourishing environment for the well-being, happiness, and material and spiritual progress (Haurvatat) of all individuals.",
                "<b>Article 2: Source and Essence of National Sovereignty</b>",
                "National sovereignty belongs solely and unconditionally to the nation of Iran, exercised democratically, in a decentralized manner, through the ballot box and elected institutions. No traditional, ideological, hereditary, or military institution has the right to usurp, suspend, or limit national sovereignty.",
                "<b>Article 3: Rule of Law and Truth (Asha)</b>",
                "The law is the manifestation of the collective will and wisdom of the nation. All laws, regulations, and judicial verdicts must align with the principles of truth, science-based justice, the International Bill of Human Rights, and environmental sustainability (Asha). No source or expediency stands above the law.",
                "",
                "Chapter II: Status, Boundaries, and Symbolic Duties of the Constitutional Monarchy (Based on the Swedish Model)",
                "<b>Article 4: Symbolic Nature and Total Separation of the Monarch from Power</b>",
                "Following the constitutional framework of Sweden (The Instrument of Government 1974), the Monarchy is a purely symbolic institution, completely devoid of any political, legislative, executive, or judicial power. The Monarch is the symbol of national unity, historical continuity, and harmony among all ethnicities and segments of Iran (Guardian of Armaiti) and is strictly barred from intervening in sovereign affairs.",
                "<b>Article 5: Removal of Executive Powers and the Nomination of the Prime Minister</b>",
                " In accordance with advanced Scandinavian (Swedish) laws, the Monarch plays no role in appointing military commanders or nominating the Prime Minister. The duty of nominating the Prime Minister and tasking them with forming the government rests entirely with the Speaker of the Parliament (the Speaker of the House of Representatives), who is elected by the people. The signing of laws by the Monarch is a purely ceremonial act, and the Monarch has no right to veto any legislation.",
                "<b>Article 6: Mechanism for Dethronement or Abdication</b>",
                "Should the Monarch violate the boundaries of the Constitution or breach their oath, as determined by the Supreme Court or a two-thirds majority of the Parliament, they shall be automatically dethroned. The Parliament shall then decide on the continuity of the institution, a change of person, or a referendum regarding the structure of the office.",
                "",
                "Chapter III: Fundamental Rights, Liberties, and Citizen Safeguards",
                "<b>Article 7: Comprehensive Equality of Gender, Ethnicity, and Belief</b>",
                " All citizens of Iran, regardless of gender, descent, language, ethnicity, race, philosophical, religious, or political views, or personal orientations, are completely equal before the law. The application of constructive affirmative action in favor of historically marginalized groups to establish true justice is lawful.",
                "<b>Article 8: Inviolability of Conscience (Daena) and the Private Sphere</b>",
                "Conscience, belief, and personal religion are strictly individual and free domains. Inquisition of beliefs and the establishment of an official state religion are prohibited in the Constitution. The residence, correspondence, digital communications, and privacy of citizens are immune from any arbitrary intrusion, wiretapping, or inspection without a clear and substantiated judicial order.",
                "<b>Article 9: Freedom of Expression, Media, and Access to Information</b>",
                "Freedom of thought, expression, press, art, and newspapers is guaranteed. Prior censorship is forbidden. Any monopoly over broadcasting media by the government or the monarchy is illegitimate. All citizens have the right to free and unfiltered access to the flow of information and the global internet.",
                "<b>Article 10: Judicial Security, Prohibition of Torture, and the Presumption of Innocence</b>",
                "Every accused person is presumed innocent until their guilt is proven in a public court, before a jury, and with the right to an independent counsel. Any physical or psychological abuse (torture), coerced confession, prolonged solitary confinement, and degrading treatment are strictly prohibited, and violators shall be prosecuted without any statute of limitations.",
                "",
                "Chapter IV: Structure of Collective Wisdom (The Bicameral Legislative Branch)",
                "<b>Article 11: The House of Representatives (Parliament)</b>",
                " This house is composed of representatives elected through nationwide, free, secret, periodic, and proportional representation elections. The primary duties of this house include enacting ordinary legislation, approving the national budget, confirming the Prime Minister, and overseeing the executive branch.",
                "<b>Article 12: The Senate of Provinces and Experts</b>",
                "This house consists of equal representatives from the provinces and scientific/specialized elites of the country to defend local interests and sustainable development at the macro level. No law shall be finalized without being reviewed by both houses to prevent the centralization of power (Vohuman).",
                "",
                "Chapter V: The Executive Branch and the Servant Government (Khshathra)",
                "<b>Article 13: Formation of the Government and Accountability (UK Constitutional Model)</b>",
                " The head of government is the Prime Minister. The leader of the party or coalition that wins the majority of seats in the House of Representatives shall be tasked with forming the cabinet. The government is fully accountable to the Parliament, and the House of Representatives can dismiss the government or any minister at any time through a vote of no confidence.",
                "<b>Article 14: Control of the Executive Power and the Military</b>",
                " Military, border control, and security forces must remain entirely non-political and non-factional, acting under the direct oversight and command of the civilian government and the Parliament. The intervention of the armed forces in economic, commercial, political, and electoral affairs is strictly prohibited and considered a criminal offense.",
                "",
                "Chapter VI: Independent Judiciary and the Arbiter of Truth (The Court of Asha)","<b></b>",
                "<b>Article 15: Absolute Independence of the Judiciary</b>",
                "The Judiciary is an independent institution whose budget, management, and administration are run by the body of judges themselves and the Supreme Judicial Council, without any interference from the government or the monarch. Judges are subservient only to the law and their own conscience in issuing verdicts, and their tenure security is guaranteed.",
                "<b>Article 16: The Parliamentary Ombudsman (Based on the Swedish Model)</b>",
                "To prevent state officials from oppressing citizens, the House of Representatives shall appoint independent ombudsmen. This office has the right to investigate complaints from citizens against government agencies, the military, and municipalities, and can challenge their actions in court.",
                "<b>Article 17: The Supreme Constitutional Court</b>",
                "This court is the ultimate authority for interpreting the Constitution and assessing the conformity of laws passed by Parliament with human rights, democracy, and the decentralization of power. Any citizen who feels that a piece of legislation or an executive action has violated their fundamental rights has the right to file a direct complaint with this court.",
                "",
                "Chapter VII: Autonomous Administration of Provinces and Distribution of Wealth",
                "<b>Article 18: Vertical Division of Power (Provincial Assemblies)</b>",
                " Iran is divided into self-governing internal regions and provinces. Affairs related to education, local culture, urban and rural development, healthcare, local police, and regional budgets are completely devolved to 'Provincial Assemblies' and 'City and Village Councils' directly elected by the people of those regions. The capital is solely responsible for foreign policy, national defense, and the national currency.",
               "<b>Article 19: Equitable Distribution of National Wealth</b>",
               "Revenue generated from the country's natural resources is the collective property of the entire nation of Iran. Nonetheless, the budget allocation mechanism must be structured in a way that assigns a special share to the producing provinces and underdeveloped regions to ensure regional balance and justice.",
               "",
               "Chapter VIII: Sustainable Development and Environmental Protection (Haurvatat and Ameretat)",
               "<b>Article 20: Sustainability of Water, Soil, and Air</b>",
               "Protecting the environment, preventing desertification, reviving wetlands and rivers, and conserving wildlife are fundamental principles of governance. Any industrial or agricultural policy that jeopardizes the environmental sustainability of Iran for future generations shall be halted and declared null and void.",
                 "<b>Article 21: Right to Welfare, Work, and Free Education</b>",
               "The government is obligated to provide a universal welfare framework, including high-quality free education up to the end of secondary school, free healthcare, and a comprehensive social security system for unemployment, old age, and disability for all citizens without any discrimination.",
                "Sources:",
               "The Root Constitution - Draft Constitution of the Constitutional Monarchy of Iran", 
               "The Gathas, the Sublime Songs of Zarathustra; Research by Dr. Khosro Khazai",
               "Best practices incorporated from the constitutional frameworks of advanced constitutional monarchies, namely Sweden (Instrument of Government 1974 and the Ombudsman system) and the United Kingdom (Parliamentary Accountability)."

                ],
                image: "pahlavi.jpg"
                },
                {
                id: "article2",
                title: "Second article Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here",
                image: "bg.jpeg"
                },
                {
                id: "article3",
                title: "Third article Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here",
                image: "kourosh.jpg"
                },
                {
                id: "article4",
                title: "Forth article Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here",
                image: "gard.jpg"
                },
                {
                id: "article5",
                title: "Fifth article Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here",
                image: "Darius.jpg"
                },
                {
                id: "article6",
                title: "Sixth article Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here",
                image: "darius-egypt.jpg"
                }
            ],
            images: ["farva.jpeg", "pasar.jpeg", "bg.jpeg"],
            video: "me1.mp4"
        }
    },
    News: {
        fa: {
            title: "تار برگ خبر",
            text: ["به تار برگ خبر خوش آمدید.",
                   " ۱. هشدار تازه درباره پیشروی فرونشست زمین در حریم تخت‌جمشید و پاسارگاد",
                   "  * تاریخ: ۲۲ شهریور ۱۴۰۵ (۱۳ سپتامبر ۲۰۲۶)",
                   "  * منبع: رادیو فردا / گزارش تحلیلی دیده‌بان میراث فرهنگی",
                    " * خلاصه خبر: با ادامه حفر بی‌رویه چاه‌های عمیق و برداشت غیرقانونی از سفره‌های آب زیرزمینی در دشت مرودشت، شکاف‌های عمیق ناشی از فرونشست زمین به فاصله خطرسازی از پایه‌های سنگی تخت‌جمشید و مجموعه پاسارگاد رسیده است. کارشناسان هشدار می‌دهند که سوءمدیریت منابع آب، این سازه‌های چند هزار ساله را در معرض آسیب ساختاری غیرقابل بازگشت قرار داده است.",
                     "* تحلیل بیدارگر (نگاه هویت‌محور): نیاکان ما با دانش کاریز و نگاه مقدس به آب و خاک، هزاره‌ها این سرزمین را آباد نگه داشتند. امروز تضاد میان خرد باستانی و ناکارآمدی ایدئولوژیک، تاریخ و جغرافیای ایران را هم‌زمان به نابودی می‌کشاند.",
                    "۲. قطعی گسترده برق صنایع و بحران انرژی در اوج گرمای تابستان",
                     "* تاریخ: ۱۸ مرداد ۱۴۰۵ (۹ اوت ۲۰۲۶)",
                     "* منبع: ایران اینترنشنال / بی‌بی‌سی فارسی",
                     "* خلاصه خبر: به دلیل ناترازی شدید در شبکه توزیع و فرسودگی زیرساخت‌های نیروگاهی، برق شهرک‌های صنعتی و بخش خانگی در اکثر استان‌های کشور به صورت روزانه و چندساعته قطع شد. این مسئله موجب توقف خطوط تولید، خسارت‌های سنگین به بخش خصوصی و کلافگی عمومی شده است.",
                     "* تحلیل بیدارگر (نگاه هویت‌محور): سرزمینی که بر روی یکی از بزرگ‌ترین ذخایر انرژی جهان قرار دارد، به دلیل صرف ثروت‌های ملی در مسیر اهداف ایدئولوژیک خارج از مرزها، از تامین اولیه انرژی برای مردم خود عاجز مانده است.",
                    "۳. ثبت رکورد تازه در مهاجرت کادر درمان و نخبگان علمی",
                     "* تاریخ: ۵ تیر ۱۴۰۵ (۲۶ ژوئن ۲۰۲۶)",
                     "* منبع: صدای آمریکا", 
                     "* خلاصه خبر: گزارش‌های جدید نهادهای صنفی و پزشکی از خروج بی‌سابقه پزشکان متخصص، پرستاران و مهندسان جوان خبر می‌دهند. نبود چشم‌انداز روشن اقتصادی، انسداد سیاسی و فشارهای اجتماعی به‌عنوان اصلی‌ترین دلایل این مهاجرت دسته‌جمعی عنوان شده است.",
                    " * تحلیل بیدارگر (نگاه هویت‌محور): توانمندی و فرّ درونی «نسل شیک» ایران که باید سرمایه آبادانی میهن باشد، به دلیل سیاست‌های تفرقه‌افکنانه خانه خراب می‌شود. راه نجات، بازآفرینی عزت‌نفس و ساختن کشوری است که شایسته فرزندان خویش باشد."
                  
                  ],
             articles:[
                {
                id: "article1",
                title: "مقاله نخست",
                summary: "خلاصه کوتاه خبر اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله "
                },
                {
                id: "article2",
                title: "مقاله دوم",
                summary: "خلاصه کوتاه خبر اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله "
                },
                {
                id: "article3",
                title: "مقاله سوم",
                summary: "خلاصه کوتاه خبر اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله "
                },
                {
                id: "article4",
                title: "مقاله چهارم",
                summary: "خلاصه کوتاه خبر اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله "
                },
                {
                id: "article5",
                title: "مقاله پنجم",
                summary: "خلاصه کوتاه خبر اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله "
                },
                {
                id: "article6",
                title: "مقاله ششم",
                summary: "خلاصه کوتاه خبر اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله "
                }
            ],
            images: [],
            video: ""
        },
        en: {
            title: "News Page Title",
            text: ["Welcome to the News page.",
                   "",
                  "1. The Encroaching Earth-Fissures Surrounding Pasargadae and Persepolis",
                   "  * Date: September 13, 2026 (22 Shahrivar 1405)",
                    " * Source: Radio Farda / Cultural Heritage Watch",
                     "* The Dispatch: Driven by indiscriminate deep-well extraction and the systemic mismanagement of subterranean aquifers across the Marvdasht plain, severe land subsidence has advanced to a perilous proximity of the ancient stone foundations of Persepolis and the Pasargadae complex. Heritage experts warn that prolonged environmental neglect now threatens these millennia-old structures with irreparable structural ruin.",
                     "* The Awakening Perspective: Our ancestors preserved this land for millennia through the sacred veneration of earth and water and the mastery of qanat engineering. Today, the stark conflict between ancient wisdom and ideological incompetence places both the history and the very geography of Iran in existential jeopardy.",
                    "",
                   "2. Widespread Power Grid Collapse and Industrial Blackouts in Midsummer",
                     "* Date: August 9, 2026 (18 Mordad 1405)",
                     "* Source: Iran International / BBC Persian",
                     "* The Dispatch: Crippled by profound energy deficits and decaying power infrastructure, rolling blackouts lasting several hours daily have swept through industrial parks and residential districts during peak summer heat. The outages have halted manufacturing, inflicted crushing losses upon private enterprise, and fueled widespread public distress.",
                     "* The Awakening Perspective: A realm endowed with one of the greatest natural energy reserves on earth is left unable to provide basic electricity to its own populace—the direct consequence of national wealth being diverted toward ideological agendas beyond its borders.",
                    "",
                   "3. Unprecedented Exodus of Healthcare Professionals and Young Scholars",
                     "* Date: June 26, 2026 (5 Tir 1405)",
                     "* Source: Voice of America (VOA) / Iran Migration Observatory",
                     "* The Dispatch: Fresh records from professional medical and engineering associations document an unprecedented wave of emigration among specialized physicians, nurses, and young innovators. Pervasive economic collapse, political suppression, and a bleak outlook for the future are cited as the primary catalysts driving this departure.",
                     "* The Awakening Perspective: The inherent potential and divine glory (Farrah) of Iran’s Chic Generation—assets meant to cultivate the motherland—are driven into exile by divisive policies. The path forward lies in reclaiming our collective dignity and rebuilding a nation worthy of its children."

                  ],
            articles:[
                {
                id: "article1",
                title: "First article Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here"
                },
                {
                id: "article2",
                title: "Second article Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here"
                },
                {
                id: "article3",
                title: "Third article Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here"
                },
                {
                id: "article4",
                title: "Forth article Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here"
                },
                {
                id: "article5",
                title: "Fifth article Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here"
                },
                {
                id: "article6",
                title: "Sixth article Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here"
                }
            ],
            images: [],
            video: ""
        }
    },
    Programs: {
        fa: {
            title: "تار برگ برنامه ها",
            text: ["به تار برگ برنامه ها خوش آمدید. این بخش به صفحات وب قابلیت‌های تعاملی اضافه می‌کند.",
                   "",
                   "برنامه‌های بازگشت به خویشتن فرهمند",
                   "",
                   "نقشه راه بیداری: بازگشت به خویشتن فرهمند و روزگار شکوه درون",
                   "",
                   "فرّ و شکوهِ ایرانی، یک افسانه‌ی فراموش‌شده در کتاب‌ها نیست؛ آتشِ زیر خاکستری است در جان و روانِ تو. وقت آن رسیده است که این گنجِ نهان را آشکار کنی.",
                   "",
                    "در روزگاری که شتابِ جهانِ نو، آدمی را از ریشه‌های خویش جدا کرده است، «برنامه‌های بیداری نسل شیک» طراحی شده‌اند تا تو را به «خویشتنِ فرهمندت» بازگردانند. فرهمندی یعنی رسیدن به آن نیروی تابناک درونی که به اندیشه‌ات روشنایی، به اراده‌ات استواری و به زندگی‌ات شکوه می‌بخشد.",
                    "ما تاریخ را نمی‌خوانیم که در گذشته بمانیم؛ تاریخ را می‌کاویم تا کدهای توانمندی و خودباوری را برای ساختنِ آینده‌ای سرافرازانه برداریم.",
                    "",
                    "برنامه‌های گام‌به‌گام برای شکوفایی توانمندی‌های نهان",
                    "",
                    "۱. کارگاه‌های بیداری فرّ درونی (دوره روان‌شناسی و خرد ایرانی)",
                     "* هدف: پیوند دادن روان‌شناسی روز جهان با الگوهای خردمندانه ایران باستان.",
                    " * آنچه به دست می‌آوری: رهایی از سردرگمی هویتی، دست‌یابی به آرامشِ استوار درونی، و یادگیریِ هنرِ «پادشاهی بر ذهن و رفتار خویشتن».",
                    "",
                    "۲. چالش‌های ۲۱ روزه خویش‌فرمانی (عادت‌سازی به سبک نیاکان)",
                    " * هدف: تبدیل اندیشه و باور به رفتار و دستاوردهای واقعی در زندگی روزمره.",
                     "* آنچه به دست می‌آوری: تمرین‌های روزانه برای تقویتِ انضباط فردی، پاک‌سازی روان از افکارِ ناتوان‌کننده، و تمرینِ گفتار، کردار و پندارِ نیک در دنیای مدرن.",
                    "",
                   " ۳. هم‌اندیشی‌های نسل شیک (نشست‌ها و گفتگوهای هم‌افزا)",
                    " * هدف: گرد هم آمدنِ ایرانیانِ آگاه، هدفمند و پیشرو که به دنبال رشد فردی و اثرگذاری اجتماعی هستند.",
                    " * آنچه به دست می‌آوری: حضور در شبکه‌ای از هم‌فکران، تبادل ایده‌های نوآورانه، و ساختن جامعه‌ای خویش‌باور و پویا.",
                    "",
                    "۴. مربی‌گری اختصاصی: «کشف جام جم درونی»",
                     "* هدف: سنجش دقیق استعدادها و ترسیم نقشه راه اختصاصی زندگی و کسب‌وکار بر پایه توانمندی‌های واقعی تو.",
                     "* آنچه به دست می‌آوری: شفافیت کامل در مسیر شغلی و شخصی، و تبدیل توانِ بالقوه به موفقیت‌های بالفعل و پایدار.",
                     "",
                    " پیمان با خویشتن",
                    " تو تنها بیننده‌ی تاریخ نیستی؛ تو نویسنده‌ی فصلِ بعدیِ این شاهکاری.",
                    " فرهمندی و شکوه، از همین لحظه و با نخستین گامی که برای شناختِ خود برمی‌داری آغاز می‌شود. خویشتنِ بزرگت در انتظارِ توست؛ او را بیدار کن!",
                    ""
                  
                  ],
            images: [],
            video: "",
            vimeoUrl: "https://player.vimeo.com/video/1203474449"
        },
        en: {
            title: " Programs for Awakening the Glorious Self",
            text: ["Welcome to the Programs page.",
                   "",
                   "The Roadmap to Awakening: Reclaiming Your Glorious Self and Inner Splendor",
                   "",
                    "The divine glory (Farrah) and splendor of the Iranian spirit are not forgotten myths locked in ancient books; they are embers beneath the ashes of your soul. The time has come to unveil this hidden treasure.",
                    "In an age where the frantic pace of the modern world has severed humanity from its roots, the Chic Generation Awakening Programs are crafted to guide you back to your, Glorious Self. Divine glory (Farrah) is that luminous inner force that brings clarity to your mind, steadfastness to your will, and majesty to your life.",
                    "We do not explore history to linger in the past; we delve into our heritage to retrieve the blueprints of capability and self-worth, forging a triumphant future.",
                    "",
                    "Step-by-Step Paths to Unlocking Your Hidden Potential",
                    "1. Workshops for Awakening the Inner Glory (Psychology & Ancient Wisdom)",
                    " * Purpose: Blending modern global psychology with the timeless wisdom of ancient Iran.",
                    " * What You Attain: Liberation from identity confusion, an unshakable inner peace, and mastery over the art of governing your own mind and conduct.",
                    "",
                   "2. 21-Day Self-Mastery Challenges (Habit-Building in the Spirit of the Ancestors)",
                     "* Purpose: Translating noble thoughts and beliefs into tangible actions and real-world achievements.",
                     "* What You Attain: Daily practices to strengthen personal discipline, cleanse the mind of limiting thoughts, and live out good thoughts, good words, and good deeds in the modern world.",
                    "",
                   "3. The Chic Generation Conclaves (Synergistic Gatherings & Dialogues)",
                     "* Purpose: Uniting conscious, purpose-driven, and forward-thinking individuals striving for personal growth and social impact.",
                     "* What You Attain: A place within a network of like-minded peers, the exchange of innovative ideas, and the building of a self-reliant, dynamic community.",
                   "",
                   "4. One-on-One Mentorship: Discovering the Cup of Jamshid Within",
                     "* Purpose: Precise assessment of your talents and crafting a personalized roadmap for your life and career based on your true capabilities.",
                    " * What You Attain: Absolute clarity in your professional and personal trajectory, converting potential energy into lasting, real-world success.",
                   "",
                   " A Covenant with Oneself",
                    " You are not merely a spectator of history; you are the author of its next glorious chapter.",
                    " Splendor and inner glory begin this very moment, with the first step you take toward self-awareness. Your greater self awaits—awaken it!"
                  ],
            images: [],
            video: "",
            vimeoUrl: "https://player.vimeo.com/video/1203474449"
        }
    },
    Hist: {
        fa: {
            title: "تار برگ تاریخ",
            text: ["به تار برگ تاریخ خوش آمدید. این بخش به صفحات وب قابلیت‌های تعاملی اضافه می‌کند. هرگز از یاد نمیبریم.",
                  "سرآغاز: سرگذشت پیشدادیان",
                   "فرنام بنیادین:",
                    "سرآغاز روشنایی و خرد؛ داستانی که از ریشه‌های تو می‌گوید",
                    "سرگذشت ما با جنگ آغاز نشد؛ با «آگاهی»، «سازندگی» و «پادشاهی بر خویشتن» آغاز شد.",
                    "بخش نخست: پیشدادیان؛ نخستین دادگستران و سازندگان جهان",
                    "داستان ما از جایی آغاز می‌شود که تاریکی و نادانی جهان را فراگرفته بود. پیشدادیان (نخستین دادگستران) آمدند تا به آدمی یاد بدهند که چگونه از هیچ، همه‌چیز بسازد.",
                    "آنان کسانی بودند که:",
                     "* آتش را نه برای ویرانی، بلکه برای گرمی و روشنایی پیدا کردند (هووشنگ).",
                     "* دبیره و نوشتن را برای رساندن دانش و خرد رام کردند (طهمورث دیوبند).",
                    "تو از تباری هستی که نخستین بار جهان را ساخت. خواستِ پیشدادیان در خون توست؛ تو برای گردن‌نهادن در برابر تاریکی‌ها ساخته نشده‌ای، تو ساخته شده‌ای تا مانند نیاکانت، روشنایی را بیافرینی.",
                    
                    "بخش دوم: روزگار جمشید؛ بالندگی خرد و جام جم درون",
                    "روزی که جمشید بر تخت نشست، روزگار زرین ایران آغاز شد. او نه با نیروی تیغ، بلکه با پزشکی، ساخت‌وساز، هنر، و جهانداری خردمندانه، بیماری، پیری و تهیدستی را از سرزمین راند. نوروز، یادگار آن جهش بزرگ اندیشه‌ای است.",
                    "جام جمشید (جام جم) چیزی جز «روانِ آگاه و آینه‌ی خودشناسی» نبود؛ ابزاری که با آن می‌شد رازهای جهان را دید.",
                    "اما جمشید یک آموزه بزرگ هم برای ما داشت: وقتی خودبینی بر خرد چیره شود، شکوه رخ برمی‌تابد.",
                    " ",
                    " جام جم در دست‌های توست. «جام جم» همان توان اندیشه و توانمندی‌های نهان توست که اگر با فروتنی و خودآگاهی همراه شود، می‌توانی روزگار زرین زندگی خودت را پی‌ریزی کنی.",
                    "", 
                    "بخش سوم: فریدون، ایرج و تور؛ نبرد بزرگ گزینش‌ها",
                    "پس از تاریکی ضحاک، فریدون نشانِ دادگری و رهایی شد. اما بزرگ‌ترین آزمون سرگذشت در نژاد او شکل گرفت: بخش‌کردن جهان میان ۳ پسرش؛ سلم، تور و ایرج.",
                     "* تور و سلم: نشانِ خشم، آز، زیاده‌خواهی و رشک‌ورزی بودند.",
                     "* ایرج: نشانِ خرد، آشتی، بزرگواریِ آدمی و گوهر اصیل بود.",
                    "ایرج جان‌باخته‌ی کینه شد، اما نام و نژادش تا جاوید نشانِ آبرو و گوهر اصیل ایرانی باقی ماند. از دل این رنج، پهلوانانی چون منوچهر و رستم زاده شدند تا نشان دهند راستی و داد هرگز خاموش نمی‌شود.",
                     " ",
                    " درون هر یک از ما نبردی میان «تور» (آز و خشم درونی) و «ایرج» (خرد و گوهر اصیل) در برپاست. سرگذشت ایران به تو یاد می‌دهد که گزینشِ «راه ایرج» یعنی گزینشِ سرترازی و آبرو، و این تنها راهی است که تو را به پهلوانِ داستانِ زندگی خودت دگرگون می‌سازد.",
                    " ",
                    "پایان‌سخن و فراخوان به کار:",
                    " تو یادگاردار این شاهکاری!",
                    " داستان پیشدادیان، افسانه‌های کهنه نیستند؛ این‌ها بن‌مایه‌هایِ باورداری و توانستن در جان و روانِ تو هستند.",
                    " اکنون نوبت توست که در روزگار نو، پیشدادیِ درون خودت را بیدار کنی. خرد جمشید، آزاده‌گی ایرج و خواستِ فریدون را بردار و آینده‌ات را بساز.",
                    " [ کلید: آشکارسازیِ توانمندی‌های درون / درآمدن به بخش خودشناسی ]",
                    " ",
                  ],
            images: [],
            video: "",
            vimeoUrl: "https://player.vimeo.com/video/1203474449"
        },
        en: {
            title: "History Page Title",
            text: ["Welcome to the History page. History makes you be aware of yourself and know about others. we never forget",
                   "The Dawn of Light and Wisdom: A Tale of Your Roots",
                    "Our history did not begin with conquest; it began with awareness, creation, and mastery over oneself.",
                    "Part I: The Pishdadians — The First Lawgivers and Builders of the World",
                    "Our story unfolds when darkness and ignorance enveloped the earth. The Pishdadians (the First Lawgivers) arose to teach humanity how to shape everything out of nothing.",
                    "They were the ones who:",
                     "* Discovered fire not for destruction, but for warmth and illumination (Houshang).",
                     "* Mastered script and writing to pass on knowledge and wisdom (Tahmuras).",
                    "",
                    " You descend from a lineage that built the world for the first time. The resolve of the Pishdadians flows in your veins; you were not forged to yield to darkness—you were forged to create light, just as your ancestors did.",
                    "",
                    "Part II: The Age of Jamshid — The Flourishing of Wisdom and the Cup Within",
                    "When Jamshid ascended the throne, the Golden Age of Iran dawned. Not through the blade of a sword, but through medicine, architecture, art, and wise governance, he banished sickness, aging, and hardship from the land. Nowruz stands as a lasting legacy of that great leap in human thought.",
                    "The Cup of Jamshid (Jam-e Jam) was nothing less than the (conscious soul and the mirror of self-awareness—)a vessel through which one could perceive the mysteries of existence.",
                    "Yet Jamshid left us a monumental lesson: When hubris triumphs over wisdom, glory slips away.",
                    "",
                    " The Cup of Jamshid is already in your hands. It represents your power of thought and your hidden potential. When paired with humility and self-awareness, you can build the Golden Age of your own life.",
                    "", 
                    "Part III: Fereydoun, Iraj, and Tur — The Great War of Choices",
                    "Following the darkness of Zahhak, Fereydoun became the symbol of justice and liberation. Yet the greatest test in history emerged within his own bloodline: the dividing of the realm among his three sons—Salm, Tur, and Iraj.",
                     "* Tur and Salm: Embodied wrath, greed, excess, and envy.",
                     "* Iraj: Embodied wisdom, peace, human dignity, and pure nobility.",
                    "Iraj fell victim to malice, yet his name and lineage remained an eternal beacon of honor and noble spirit. From the depths of this grief, heroes such as Manuchehr and Rostam were born, proving that truth and justice are never extinguished.",
                    "",
                    " Within each of us, a battle rages between Tur (inner greed and wrath) and Iraj (wisdom and noble character). History teaches you that choosing the Path of Iraj, means choosing dignity and honor—and that is the sole path that transforms you into the hero of your own life story.",
                    "", 
                    " Closing Word and Call to Action:",
                    " You are the Guardian of This Masterpiece!",
                    " The stories of the Pishdadians are not ancient myths; they are the fundamental blueprints of belief and capability within your spirit.",
                    " Now it is your turn to awaken the Pishdadian within yourself in this modern era. Harness the wisdom of Jamshid, the noble freedom of Iraj, and the resolve of Fereydoun to forge your future.",
                    " [ Button: Unlock Your Inner Potential / Enter the Journey of Self-Discovery ]",
                    ""    
                  ],
            images: [],
            video: "",
            vimeoUrl: "https://player.vimeo.com/video/1203474449"
        }
    },
    // Dropdown items can live here too!
    tutorials: {
        fa: { title: "تار برگ اصلی آموزش‌ها", text: "به مرکز آموزش‌های ما خوش آمدید. در این بخش می‌توانید آموزش‌های مختلف را پیدا کنید.", 
              articles:[
                {
                id: "article1",
                title: "آموزش نخست بازاندیشی:",
                summary: "هنر سنجیدن و درست اندیشیدن",

                fullText:[ 
                    
                  "<b>هر دگرگونی بزرگی، نخست از یک پرسش کوچک آغاز می‌شود:</b>",
                "«از کجا بدانم آنچه باور دارم، به‌راستی درست است؟»",
                "شاید این ساده‌ترین و در همان حال، ژرف‌ترین پرسشی باشد که یک آدمی می‌تواند از خود بپرسد.",
                "ما از همان روزهای نخست زندگی، چیزهای بسیاری می‌آموزیم.",
                "از خانواده، مدرسه، دوستان، آموزگاران، کتاب‌ها، رسانه‌ها، آیین‌ها، پیرامون خود و مردمانی که به آنان اعتماد داریم.",
                "بسیاری از این آموخته‌ها ارزشمندند.",
                "اما یک نکته را نباید فراموش کنیم:",
                "آنچه به ما آموخته‌اند، الزاماً همان چیزی نیست که خودمان سنجیده‌ایم.",
                "اندیشه‌ای که بارها شنیده‌ایم، ممکن است برایمان همچون یک حقیقت بدیهی به نظر برسد.",
                "باوری که از کودکی با آن بزرگ شده‌ایم، ممکن است آن‌چنان با زندگی ما درآمیخته باشد که دیگر به ذهنمان نرسد از خود بپرسیم:",
                "چرا این را باور دارم؟",
                "اینجاست که بازاندیشی آغاز می‌شود.",
                "---",
                "<b>اندیشیدن دربارهٔ اندیشه</b>",
                "اندیشه‌ورزی تنها داشتن اندیشه نیست.",
                "بازاندیشی یعنی بتوانیم به اندیشه‌های خود نیز بنگریم.",
                "یعنی بتوانیم باور خود را برای مدتی کنار بگذاریم و مانند یک پژوهشگر، آن را بررسی کنیم.",
                "نه برای اینکه حتماً آن را کنار بگذاریم؛",
                "بلکه برای اینکه بدانیم چرا آن را پذیرفته‌ایم.",
                "از خود بپرسیم:",
                "- این سخن دقیقاً چه می‌گوید؟",
                "- از کجا آمده است؟",
                "- چه کسانی آن را می‌گویند؟",
                "- چه گواهی برای آن داریم؟",
                "- آیا گواه‌ها درست و سنجیدنی هستند؟",
                "- آیا گواه دیگری هم وجود دارد؟",
                "- آیا می‌توان برداشت دیگری از همین داده‌ها داشت؟",
                "- آیا چیزی را تنها به این دلیل پذیرفته‌ام که دوست دارم درست باشد؟",
                "- اگر گواهی نیرومند بر ضد باورم پیدا شود، آیا آماده‌ام دیدگاهم را دگرگون کنم؟",
                "این‌ها پرسش‌های ساده‌ای هستند.",
                "اما آدمی که به‌راستی آنها را از خود می‌پرسد، دیگر همان آدم پیشین نیست.",
                "---",
                "<b>چرا بازاندیشی اهمیت دارد؟</b>",
                "ما در جهانی زندگی می‌کنیم که هر روز هزاران سخن به سوی ما روانه می‌شود.",
                "خبر.",
                "تصویر.",
                "ویدیو.",
                "نوشته.",
                "داستان.",
                "شایعه.",
                "آگهی.",
                "گفتار سیاسی.",
                "گزارش علمی.",
                "دیدگاه یک دوست.",
                "دیدگاه یک دشمن.",
                "و گاهی سخنی که بسیار زیبا و دلنشین است، اما هیچ گواهی برای درستی آن وجود ندارد.",
                "ذهن آدمی همیشه میان حقیقت و نادرستی، خودبه‌خود داوری درستی نمی‌کند.",
                "گاهی چیزی را باور می‌کنیم چون بارها شنیده‌ایم.",
                "گاهی چون گوینده را دوست داریم.",
                "گاهی چون از گوینده بیزاریم و بنابراین هرچه می‌گوید را نادرست می‌دانیم.",
                "گاهی چون سخن با باورهای پیشین ما سازگار است.",
                "و گاهی تنها به این دلیل که سخن، احساس نیرومندی در ما پدید آورده است.",
                "پس نخستین گام برای آزاداندیشی این است:",
                "«هر سخنی را که می‌شنویم، بی‌درنگ باور نکنیم؛ و هر سخنی را که دوست نداریم نیز بی‌درنگ نادرست ندانیم.»",
                "---",
                "<b>«نمی‌دانم» یک پاسخ ارزشمند است</b>",
                "یکی از دشوارترین واژه‌ها برای آدمی، شاید همین باشد:",
                "<b>نمی‌دانم.</b>",
                "بسیاری از ما دوست داریم برای هر پرسشی پاسخی داشته باشیم.",
                "اما ندانستن، ناتوانی نیست.",
                "پذیرفتن ندانستن، آغاز دانستن است.",
                "سه حالت را از هم جدا کنیم:",
                "<b>می‌دانم.</b>",
                "<b>می‌دانم که نمی‌دانم.</b>",
                "<b>نمی‌دانم که نمی‌دانم.</b>",
                "سومی خطرناک‌تر است؛ زیرا ممکن است درباره چیزی با اطمینان سخن بگوییم که هرگز آن را بررسی نکرده‌ایم.",
                "پس هرگاه گواه کافی نداریم، می‌توانیم بگوییم:",
                "«هنوز نمی‌دانم.»",
                "این پاسخ نه شکست است و نه شرمندگی.",
                "این پاسخ یعنی:",
                "راه جست‌وجو هنوز باز است.",
                "---",
                "<b>احساس، دشمن اندیشه نیست</b>",
                "اندیشیدن درست به این معنا نیست که احساسات خود را کنار بگذاریم.",
                "ترس، خشم، شادی، اندوه، امید، مهر و دلبستگی، بخش‌هایی از زندگی آدمی هستند.",
                "اما باید میان احساس و گواه دگرسانی بگذاریم.",
                "ممکن است از چیزی بترسیم.",
                "این ترس واقعی است.",
                "اما واقعی بودن ترس، به‌تنهایی نشان نمی‌دهد که چیزی که از آن می‌ترسیم، واقعاً خطرناک است.",
                "ممکن است از کسی خشمگین باشیم.",
                "خشم ما واقعی است.",
                "اما خشم، به‌تنهایی نشان نمی‌دهد که برداشت ما از رفتار آن شخص درست بوده است.",
                "بنابراین پیش از یک داوری مهم، لحظه‌ای درنگ کنیم:",
                "«اکنون چه احساسی دارم؟»",
                "سپس بپرسیم:",
                "«چه گواهی برای داوری خود دارم؟»",
                "و در پایان:",
                "«آیا احساس خود را با حقیقت یکی گرفته‌ام؟»",
                "---",
                "<b>سخن را از گوینده جدا کنیم</b>",
                "یک سخن ممکن است درست باشد، حتی اگر گویندهٔ آن را دوست نداشته باشیم.",
                "و یک سخن ممکن است نادرست باشد، حتی اگر گویندهٔ آن را بسیار دوست داشته باشیم.",
                "پس به جای اینکه بگوییم:",
                "«او آدم خوبی است، پس حرفش درست است.»",
                "یا:",
                "«من از او بیزارم، پس حرفش غلط است.»",
                "بپرسیم:",
                "«خود این سخن چه گواهی دارد؟»",
                "این یکی از پایه‌های آزاداندیشی است.",
                "نه نام گوینده باید جای گواه را بگیرد، نه دشمنی با گوینده.",
                "---",
                "<b>سخت‌گیری را نخست بر خودمان به کار ببریم</b>",
                "سنجش دیگران آسان است.",
                "سنجش خود، دشوار است.",
                "ممکن است ساعت‌ها برای یافتن خطای یک دیدگاه مخالف جست‌وجو کنیم، اما برای باور خودمان حتی چند دقیقه هم وقت نگذاریم.",
                "پس یک آزمایش ساده انجام دهیم:",
                "«اگر همین سخن را کسی که با او مخالفم می‌گفت، آیا باز هم آن را می‌پذیرفتم؟»",
                "و یک پرسش دشوارتر:",
                "«چه گواهی می‌تواند نظر مرا دگرگون کند؟»",
                "اگر پاسخ این باشد:",
                "«هیچ چیز»",
                "شاید دیگر با یک دیدگاه سنجیدنی روبه‌رو نیستیم.",
                "آزاداندیشی یعنی آماده باشیم که در برابر گواه بهتر، نظر خود را دگرگون کنیم.",
                "دگرگون کردن یک باور نادرست، شکست نیست؛ پیروزی بر نادرستی است.",
                "---",
                "<b>حقیقت را با خواستهٔ خود یکی نگیریم</b>",
                "یکی از دشوارترین دام‌ها این است که چیزی را چون می‌خواهیم درست باشد، درست بپنداریم.",
                "امید می‌تواند ارزشمند باشد.",
                "اما امید، گواه نیست.",
                "آرزو می‌تواند زیبا باشد.",
                "اما آرزو، گواه نیست.",
                "خشم می‌تواند نیرومند باشد.",
                "اما خشم، گواه نیست.",
                "و ترس می‌تواند شدید باشد.",
                "اما ترس، گواه نیست.",
                "پس همواره بکوشیم میان این سه چیز مرز بگذاریم:",
                "<b>آنچه می‌دانم</b>",
                "<b>آنچه گمان می‌کنم</b>",
                "<b>آنچه آرزو می‌کنم</b>",
                "گاهی این سه با یکدیگر آمیخته می‌شوند.",
                "کار اندیشه، جدا کردن آنهاست.",
                "---",
                "<b>گواه، نه شمارِ باورمندان</b>",
                "اگر هزار نفر چیزی را باور داشته باشند، آیا آن چیز حتماً درست است؟",
                "نه.",
                "اگر تنها یک نفر چیزی را باور داشته باشد، آیا حتماً نادرست است؟",
                "باز هم نه.",
                "درستی یک سخن را شمار باورمندان آن تعیین نمی‌کند.",
                "آنچه اهمیت دارد، گواه و استدلال است.",
                "پس به جای:",
                "«همه این را می‌گویند.»",
                "بپرسیم:",
                "«گواه آن چیست؟»",
                "---",
                "<b>هر ادعا را به اجزای کوچک‌تر بشکنیم</b>",
                "گاهی یک سخن به گونه‌ای گفته می‌شود که بزرگ و پیچیده به نظر می‌رسد.",
                "آن را خرد کنیم.",
                "برای نمونه، اگر کسی بگوید:",
                "«این کار همیشه باعث پیشرفت جامعه می‌شود.»",
                "پرسش کنیم:",
                "«همیشه» یعنی چه؟",
                "«پیشرفت» چگونه سنجیده شده است؟",
                "در کدام جامعه؟",
                "در چه زمانی؟",
                "چه گواهی برای رابطهٔ میان این کار و پیشرفت وجود دارد؟",
                "با این کار، یک سخن مبهم تبدیل به چند پرسش روشن می‌شود.",
                "و پرسش روشن، بسیار آسان‌تر سنجیده می‌شود.",
                "---",
                "<b>پنج گام برای سنجش یک سخن</b>",
                "از امروز می‌توانیم برای بررسی هر ادعا از این روش ساده بهره بگیریم.",
                "<b>گام یک: ادعا را روشن کن</b>",
                "دقیقاً چه چیزی گفته شده است؟",
                "<b>گام دو: سرچشمه را پیدا کن</b>",
                "این سخن از کجا آمده است؟",
                "<b>گام سه: گواه را بخواه</b>",
                "چه چیزی آن را پشتیبانی می‌کند؟",
                "<b>گام چهار: دیدگاه‌های دیگر را ببین</b>",
                "آیا گواه یا برداشت دیگری وجود دارد؟",
                "<b>گام پنج: اندازهٔ اطمینان خود را بسنج</b>",
                "آیا باید بگویم:",
                "مطمئنم؟",
                "گمان می‌کنم؟",
                "یا:",
                "هنوز نمی‌دانم؟",
                "این گام آخر بسیار مهم است.",
                "زیرا همه چیز سیاه و سفید نیست.",
                "گاهی بهترین پاسخ:",
                "«شواهد کنونی برای یک داوری قطعی بسنده نیست.»",
                "است.",
                "---",
                "<b>چند دام اندیشه</b>",
                "ذهن آدمی گاهی میانبر می‌زند.",
                "شناختن این میانبرها به ما کمک می‌کند کمتر گرفتار آنها شویم.",
                "<b>حمله به گوینده</b>",
                "به جای پاسخ دادن به سخن، به خود شخص حمله کنیم.",
                "<b>دوگانه‌سازی</b>",
                "فقط دو راه ببینیم:",
                "«یا با منی یا دشمن من.»",
                "در حالی که ممکن است راه‌های بسیار دیگری وجود داشته باشد.",
                "<b>گزینش گواه</b>",
                "فقط گواه‌هایی را ببینیم که باور پیشین ما را پشتیبانی می‌کنند.",
                "<b>پیروی از شمار بیشتر</b>",
                "«همه می‌گویند، پس درست است.»",
                "<b>پیروی از نام و جایگاه</b>",
                "«فلان فرد نامدار گفته، پس درست است.»",
                "<b>پیوند دادن دو رخداد</b>",
                "دو رخداد پس از یکدیگر رخ داده‌اند و نتیجه بگیریم یکی حتماً دیگری را پدید آورده است.",
                "اینها تنها چند نمونه‌اند.",
                "شناخت این دام‌ها به ما کمک می‌کند پیش از داوری، اندکی درنگ کنیم.",
                "---",
                "<b>یک تمرین روزانه</b>",
                "از امروز، هر روز تنها یک ادعا را بررسی کن.",
                "ادعایی دربارهٔ هر چیزی:",
                "دانش.",
                "تاریخ.",
                "اقتصاد.",
                "فرهنگ.",
                "جامعه.",
                "فناوری.",
                "یا زندگی روزمره.",
                "آن را بنویس.",
                "سپس این شش پرسش را پاسخ بده:",
                "<b>۱. ادعا دقیقاً چیست؟</b>",
                "<b>۲. گوینده یا سرچشمهٔ آن کیست؟</b>",
                "<b>۳. چه گواهی برای آن ارائه شده است؟</b>",
                "<b>۴. آیا گواه را می‌توان از سرچشمه‌ای دیگر بررسی کرد؟</b>",
                "<b>۵. آیا توضیح دیگری برای این داده‌ها وجود دارد؟</b>",
                "<b>۶. چه چیزی می‌تواند نظر مرا دگرگون کند؟</b>",
                "اگر این کار را هر روز انجام دهی، شاید در آغاز تنها یک تمرین به نظر برسد.",
                "اما به‌تدریج روش نگاه کردن تو به جهان دگرگون خواهد شد.",
                "---",
                "<b>دشوارترین تمرین</b>",
                "اکنون یک باور مهم خودت را انتخاب کن.",
                "باوری که برایت ارزشمند است.",
                "سپس تلاش کن نیرومندترین استدلال بر ضد آن را پیدا کنی.",
                "نه یک سخن ضعیف.",
                "نه سخنی که به آسانی بتوانی مسخره‌اش کنی.",
                "بلکه بهترین استدلالی که یک آدم خردمندِ مخالف دیدگاه تو می‌تواند ارائه دهد.",
                "آن را با دقت بخوان.",
                "سپس از خود بپرس:",
                "«آیا پاسخی برای آن دارم؟»",
                "اگر داری، پاسخ خود را بیازمای.",
                "اگر نداری، نگران نباش.",
                "شاید باید بیشتر بیاموزی.",
                "و شاید باید بخشی از دیدگاه خود را دگرگون کنی.",
                "توانایی تغییر دادن اندیشه در برابر گواه بهتر، نشانهٔ سستی نیست؛ نشانهٔ آزاد بودن اندیشه است.",
                "---",
                "<b>بازگشت به خود</b>",
                "«بازگشت به خود» الزاماً بازگشت به گذشته نیست.",
                "شاید به معنای بازگشت به توانایی‌هایی باشد که هر آدمی از آغاز با خود دارد:",
                "پرسشگری.",
                "کنجکاوی.",
                "آزاداندیشی.",
                "راستگویی با خویشتن.",
                "پذیرش نادانستن.",
                "شنیدن سخن مخالف.",
                "توانایی گفتنِ «اشتباه کردم».",
                "توانایی دگرگون کردن دیدگاه.",
                "اینها نشانه‌های یک ذهن زنده‌اند.",
                "جامعه‌ای که آدم‌های آن بتوانند مستقل بیندیشند، کمتر اسیر شایعه، ترس، فریب و فرمان‌برداری کور خواهد شد.",
                "چنین آدم‌هایی لازم نیست همیشه با یکدیگر هم‌نظر باشند.",
                "در حقیقت، شاید هرگز هم‌نظر نشوند.",
                "اما می‌توانند بیاموزند که چگونه با وجود ناهمسانی دیدگاه‌ها، یکدیگر را انسان بدانند.",
                "و این آغاز ساختن یک جامعهٔ بالنده است.",
                "---",
                "<b>برای نسل پاسارگاد</b>",
                "ما وارث هزاران سال تاریخیم.",
                "اما میراث یک ملت تنها سنگ‌ها، بناها، پادشاهان و جنگ‌ها نیست.",
                "میراث یک ملت، توانایی آن برای آموختن از گذشته و ساختن آینده نیز هست.",
                "اگر می‌خواهیم آینده‌ای دیگر داشته باشیم، نخست باید یاد بگیریم که چگونه بیندیشیم.",
                "نه آن‌گونه که دیگری از ما می‌خواهد.",
                "نه آن‌گونه که ترس به ما فرمان می‌دهد.",
                "نه آن‌گونه که خشم لحظه‌ای حکم می‌کند.",
                "بلکه با چشم باز، ذهن پرسشگر و وجدان بیدار.",
                "پاسارگاد تنها یک جای باستانی نیست.",
                "می‌تواند یادآور این باشد که یک نسل می‌تواند چیزی فراتر از زمان خود به جا بگذارد.",
                "اما آینده را نمی‌توان تنها با یاد گذشته ساخت.",
                "باید شایستگی ساختن آینده را نیز در خود پرورش دهیم.",
                "از یک پرسش آغاز کنیم.",
                "از یک اندیشه.",
                "از یک گفت‌وگو.",
                "از یک انسان که تصمیم می‌گیرد دیگر هر سخنی را بی‌بررسی نپذیرد.",
                "و شاید از همین‌جا، چیزی بزرگ‌تر آغاز شود:",
                "«نسلی که پیش از دگرگون کردن جهان، آموخت چگونه خودش را بسنجد.»",
                "<b>فکر کن.</b>",
                "<b>بپرس.</b>",
                "<b>بسنج.</b>",
                "<b>بشنو.</b>",
                "<b>اگر اشتباه کردی، بپذیر.</b>",
                "<b>اگر گواه بهتری یافتی، دگرگون شو.</b>",
                "<b>و دوباره بیندیش.</b>",
                "<b>این نخستین گامِ بازگشت به خود است.</b>"
                
                
                ]
                },
                {
                id: "article2",
                title: "آموزش دوم",
                summary: "خلاصه آموزش اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله "
                },
                {
                id: "article3",
                title: "آموزش سوم",
                summary: "خلاصه آموزش اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله "
                },
                {
                id: "article4",
                title: "آموزش چهارم",
                summary: "خلاصه آموزش اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله "
                },
                {
                id: "article5",
                title: "آموزش پنجم",
                summary: "خلاصه آموزش اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله "
                },
                {
                id: "article6",
                title: "آموزش ششم",
                summary: "خلاصه آموزش اینجا قرار میگیرد...",
                fullText:"اینجا قرار میگیرد متن کامل مقاله "
                }
             ]
            },
        en: { title: "Tutorials Home", text: "Welcome to our Tutorials center. Here you can find various educational topics.",
             articles:[
                {
                id: "article1",
                title: "Lesson One: Re-Thinking",
                summary: "The Art of Reason and Discernment",
                fullText:[
                    "<b>Every grand transformation begins with a single, quiet question:</b>",
                    "“How do I truly know that what I believe is right?”",
                    "It is perhaps the simplest, yet most profound query a human being can ponder.",
                    "From our earliest days, we inherit a vast tapestry of thought—from family and schools, friends and mentors, books and media, traditions and the culture of those we trust. Much of this wisdom is invaluable. Yet, we must never forget one essential truth:",
                    "What we have been taught is not necessarily what we have examined for ourselves.",
                    "An idea heard a thousand times may begin to feel like self-evident truth. A belief nurtured since childhood can become so interwoven with our identity that we forget to pause and ask: Why do I hold this to be true?",
                    "Here lies the awakening of re-thinking.",
                    "---",
                    "<b>Thinking Upon Thought</b>",
                    "True intellect is not merely the possession of thoughts; it is the capacity to observe one's own mind.",
                    "Re-thinking means setting our convictions aside for a moment to examine them as an impartial seeker—not to cast them away out of hand, but to understand why we accepted them in the first place.",
                    "We must dare to ask:",
                    "- What is this statement precisely asserting?",
                    "- Where does it originate, and who speaks it?",
                    "- What evidence supports it, and is that evidence verifiable?",
                    "- Are there alternative interpretations of the same data?",
                    "- Have I accepted this merely because I wish it to be true?",
                    "- If compelling evidence contradicts my view, am I prepared to evolve?",
                    "These are simple questions, yet the individual who asks them sincerely is no longer the same person they were before.",
                    "---",
                    "<b>Why Re-Thinking Matters</b>",
                    "We inhabit a world flooded with daily assertions—news, images, videos, political discourse, scientific reports, rumors, advertisements, and the opinions of friends and foes alike. Some words are wrapped in eloquence, yet rest upon no foundation of truth.",
                    "The human mind does not naturally discern truth from falsehood. We are prone to believe what we hear repeatedly, what comes from those we admire, or what aligns with our existing biases and emotions.",
                    "Thus, the first step toward free thought is this: Do not instantly accept what pleases you, nor instantly reject what unnerves you.",
                    "---",
                    "<b>“I Do Not Know” is a Sacred Statement</b>",
                    "Among the most difficult phrases for mankind to utter is simply:",
                    "<b>“I do not know.”</b>",
                    "Yet, admitting ignorance is not weakness; it is the threshold of enlightenment. We must distinguish between three states:",
                    "<b>What I know.</b>",
                    "<b>What I know I do not know.</b>",
                    "<b>What I do not know I do not know.</b>",
                    "The third is the most perilous. When evidence is insufficient, saying “I do not yet know” is neither defeat nor shame. It signifies that the path of inquiry remains open.",
                    "---",
                    "<b>Emotion is Not the Enemy of Reason</b>",
                    "To think clearly does not mean extinguishing emotion. Fear, rage, joy, sorrow, and devotion are fundamental to the human experience. However, we must separate emotion from evidence.",
                    "Fear may be real, but its presence alone does not prove the threat is genuine. Anger may be intense, but it does not validate our interpretation of another's intent. Before passing judgment, pause and ask:",
                    "- What am I feeling right now?",
                    "- What evidence do I possess?",
                    "- Am I mistaking my emotion for the truth?",
                    "---",
                    "<b>Separate the Message from the Messenger</b>",
                    "A statement may be true even if spoken by an adversary, just as a statement may be false even if spoken by a beloved ally.",
                    "Replace the temptation to say, \"They are good, so they must be right,\" or \"I despise them, so they must be wrong,\" with a single objective inquiry:",
                    "<b>“What evidence supports the statement itself?”</b>",
                    "---",
                    "<b>Scrutinize Yourself First</b>",
                    "It is easy to critique others, yet formidable to examine oneself.",
                    "Test your convictions with this exercise:",
                    "> \"If this exact statement were spoken by someone I oppose, would I still accept it?\"",
                    "And ask the ultimate question:",
                    "> \"What evidence would it take to change my mind?\"",
                    "If the answer is \"nothing,\" you are no longer dealing with a reasoned perspective. Changing a belief in the light of better evidence is not a defeat—it is a triumph over error.",
                    "---",
                    "<b>Do Not Confuse Truth with Desire</b>",
                    "Hope, desire, anger, and fear are powerful, but none of them constitute proof. We must constantly delineate between:",
                    "<b>What I know</b>",
                    "<b>What I assume</b>",
                    "<b>What I desire</b>",
                    "The duty of the mind is to untangle these three strands.",
                    "---",
                    "<b>Evidence, Not the Volume of Believers</b>",
                    "If a thousand people believe a falsehood, it does not become truth. If a lone voice stands by a proven fact, it does not become false. Truth is not determined by consensus, but by evidence and sound reason.",
                    "Instead of declaring, \"Everyone says so,\" ask:",
                    "<b>“Where is the proof?”</b>",
                    "---",
                    "<b>Deconstruct Complex Claims</b>",
                    "When confronted with grand or ambiguous statements, break them down. If someone claims, \"This action always brings progress,\" ask:",
                    "- What is meant by \"always\"?",
                    "- How is \"progress\" measured?",
                    "- In which society, and under what conditions?",
                    "Deconstructing ambiguity into precise questions makes discernment manageable.",
                    "---",
                    "<b>Five Steps to Evaluate Any Claim</b>",
                    "<b>Clarify the Claim:</b> What exactly is being asserted?",
                    "<b>Trace the Source:</b> Where does this statement originate?",
                    "<b>Demand Evidence:</b> What facts support it?",
                    "<b>Seek Alternative Views:</b> Are there other interpretations or counter-evidence?",
                    "<b>Gauge Your Confidence:</b> Am I certain, assuming, or do I not yet know?",
                    "---",
                    "<b>Common Pitfalls of Thought</b>",
                    "<b>Ad Hominem:</b> Attacking the speaker instead of the argument.",
                    "<b>False Dilemma:</b> Forcing a choice between only two extremes (\"You are either with me or against me\").",
                    "<b>Confirmation Bias:</b> Selecting only the evidence that supports prior beliefs.",
                    "<b>Appeal to Popularity:</b> Believing something simply because the majority does.",
                    "<b>Appeal to Authority:</b> Accepting claims blindly based solely on a title or name.",
                    "<b>False Causality:</b> Assuming that because one event followed another, the first caused the second.",
                    "---",
                    "<b>A Daily Exercise</b>",
                    "Select one claim each day—from history, science, culture, or daily life—and answer these six questions:",
                    "<b>1. What is the claim?</b>",
                    "<b>2. Who is the source?</b>",
                    "<b>3. What evidence is provided?</b>",
                    "<b>4. Can the evidence be independently verified?</b>",
                    "<b>5. Is there an alternative explanation?</b>",
                    "<b>6. What could alter my conclusion?</b>",
                    "Practiced daily, this simple exercise will fundamentally refine how you perceive the world.",
                    "---",
                    "<b>The Ultimate Challenge</b>",
                    "Select a cherished belief you hold dear. Seek out the strongest, most intelligent counter-argument against it. Read it with care and ask yourself: Do I have a reasoned response?",
                    "If you do, test it. If you do not, embrace the opportunity to learn—or the courage to evolve. The capacity to adjust one's view in the presence of greater truth is the ultimate mark of a free mind.",
                    "---",
                    "<b>The Return to Self</b>",
                    "A \"return to self\" is not a retreat into the past, but a reclamation of our innate human capacities: curiosity, questioning, intellectual courage, and the honesty to admit error.",
                    "A society composed of independent thinkers is resilient against deception, fear, and blind obedience. Such individuals need not agree on everything; rather, they learn to honor each other's humanity amidst disagreement. This is the cornerstone of a thriving civilization.",
                    "---",
                    "<b>For the Pasargad Generation</b>",
                    "We are the custodians of a millennia-old legacy. Yet, the true heritage of a nation lies not merely in its ancient stones, monuments, and kings, but in its enduring capacity to learn from history and forge the future.",
                    "To build a new era, we must first master how to think—not as fear dictates, nor as passing anger demands, but with open eyes, a questioning mind, and an awakened conscience.",
                    "Pasargad is more than a historic sanctuary; it is a testament that a generation can leave behind something greater than itself.",
                    "Start with a single question. A single thought. A single conversation. Begin as one who refuses to accept claims without reflection.",
                    "<b>Think.</b>",
                    "<b>Question.</b>",
                    "<b>Evaluate.</b>",
                    "<b>Listen.</b>",
                    "<b>If you err, acknowledge it.</b>",
                    "<b>If you find better evidence, evolve.</b>",
                    "<b>And think anew.</b>",
                    "<b>This is the first step of the return to self.</b>",
                    "<b>The Pasargad Generation.</b>"

                ]
                },
                {
                id: "article2",
                title: "Second lesson Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here"
                },
                {
                id: "article3",
                title: "Third lesson Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here"
                },
                {
                id: "article4",
                title: "Forth lesson Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here"
                },
                {
                id: "article5",
                title: "Fifth lesson Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here"
                },
                {
                id: "article6",
                title: "Sixth lesson Title",
                summary: "Short preview summary goes here",
                fullText:"Full article text that appear after clicking apears here"
                }
               ]
            }
    },
    References: {
        fa: { title: "مراجع", text: "به مرکز آموزش‌های ما خوش آمدید. در این بخش می‌توانید مراجع مختلف را پیدا کنید." },
        en: { title: "References Home", text: "Welcome to our references page. Here you can find all documentations and resources." }
    },
    Examples: {
        fa: { title: "نمونه ها", text: "به مرکز آموزش‌های ما خوش آمدید. در این بخش می‌توانید مراجع مختلف را پیدا کنید." 
        },
        en: { title: "Example Home", text: "Welcome to our references page. Here you can find all documentations and resources." }
    },
    contact: {
        fa: { title: "پیوند با ما", text: "به مرکز آموزش‌های ما خوش آمدید. در این بخش می‌توانید مراجع مختلف را بفرستید.",
            isContactPage: true
         },
        en: { title: "Contact us", text: "Welcome to our contact. Here you can upload all documentations and resources.",
            isContactPage: true
         }
    }

};
